import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const URL=Deno.env.get('SUPABASE_URL')!;
const SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||Deno.env.get('SUPABASE_SECRET_KEY')!;
const ANON=Deno.env.get('SUPABASE_ANON_KEY')||Deno.env.get('SUPABASE_PUBLISHABLE_KEY')!;
const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,apikey,content-type','Access-Control-Allow-Methods':'POST,OPTIONS'};
const json=(v:unknown,s=200)=>new Response(JSON.stringify(v),{status:s,headers:{...CORS,'Content-Type':'application/json'}});
const admin=createClient(URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:CORS});if(req.method!=='POST')return json({error:'Method not allowed'},405);try{const auth=req.headers.get('Authorization');if(!auth)return json({error:'Authentication required'},401);const c=createClient(URL,ANON,{global:{headers:{Authorization:auth}}});const {data:{user},error}=await c.auth.getUser(auth.replace(/^Bearer\s+/i,''));if(error||!user)return json({error:'Invalid authentication'},401);const b=await req.json() as any;const content=String(b.content||'').trim();const media=Array.isArray(b.media_urls)?b.media_urls.slice(0,20):[];const visibility=['public','unlisted','followers','private'].includes(b.visibility)?b.visibility:'public';if(!content&&!media.length)return json({error:'Post must contain text or media'},400);if(content.length>10000)return json({error:'Post is too long'},413);const row={author_id:user.id,user_id:user.id,content,media_urls:media,image_url:typeof b.image_url==='string'?b.image_url:null,video_url:typeof b.video_url==='string'?b.video_url:null,is_video:Boolean(b.is_video),visibility,community_id:b.community_id||null};const {data:post,error:insertError}=await admin.from('posts').insert(row).select('*').single();if(insertError)return json({error:'Post creation failed',detail:insertError.message},400);return json({ok:true,post},201)}catch(e){console.error(e);return json({error:e instanceof Error?e.message:'Post creation failed'},500)}})
