const AP='application/ld+json; profile="https://www.w3.org/ns/activitystreams", application/activity+json';
const CTX=['https://www.w3.org/ns/activitystreams','https://w3id.org/security/v1'];
const DOMAIN='federation.testagram.site';
const ORIGIN=`https://${DOMAIN}`;
const enc=(s:string)=>encodeURIComponent(s);
const b64=(x:ArrayBuffer|Uint8Array)=>btoa(String.fromCharCode(...new Uint8Array(x)));
const ub64=(s:string)=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
function ap(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/activity+json; charset=utf-8','Cache-Control':'no-store','Access-Control-Allow-Origin':'*'}})}
async function db(e:any,path:string,init:RequestInit={}){const h=new Headers(init.headers);h.set('apikey',e.SUPABASE_SECRET_KEY);h.set('Authorization',`Bearer ${e.SUPABASE_SECRET_KEY}`);h.set('Content-Type','application/json');const r=await fetch(`${e.SUPABASE_URL}/rest/v1/${path}`,{...init,headers:h});if(!r.ok)throw new Error(`db ${r.status}: ${(await r.text()).slice(0,500)}`);return r}
async function actor(e:any,username:string){const r=await db(e,`federation_actors?username=eq.${enc(username)}&select=*&limit=1`);return (await r.json() as any[])[0]||null}
async function signedGet(local:any,url:string){const u=new URL(url),date=new Date().toUTCString(),key=await crypto.subtle.importKey('jwk',local.private_key_jwk,{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign']),canonical=`(request-target): get ${u.pathname}${u.search}\nhost: ${u.host}\ndate: ${date}`,sig=await crypto.subtle.sign('RSASSA-PKCS1-v1_5',key,new TextEncoder().encode(canonical));return fetch(url,{headers:{Date:date,Accept:AP,Signature:`keyId="${local.actor_url}#main-key",algorithm="rsa-sha256",headers="(request-target) host date",signature="${b64(sig)}"`,'User-Agent':'Testagram-Federation/2.0'}})}
function sigParts(v:string){const out:Record<string,string>={};for(const p of v.split(/,(?=\w+=)/)){const i=p.indexOf('=');if(i>0)out[p.slice(0,i).trim()]=p.slice(i+1).trim().replace(/^"|"$/g,'')}return out}
async function verify(e:any,req:Request,body:string,local:any){const sh=req.headers.get('Signature'),date=req.headers.get('Date'),digest=req.headers.get('Digest');if(!sh||!date||!digest)throw new Error('Missing ActivityPub signature headers');const ts=Date.parse(date);if(!Number.isFinite(ts)||Math.abs(Date.now()-ts)>12*60*60*1000)throw new Error('Stale ActivityPub signature');const expected=`sha-256=${b64(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(body)))}`;if(digest!==expected&&digest!==expected.replace('sha-256=','SHA-256='))throw new Error('Digest mismatch');const p=sigParts(sh);if(!p.keyId||!p.signature)throw new Error('Malformed ActivityPub signature');const remoteActorUri=p.keyId.split('#')[0];const rr=await signedGet(local,remoteActorUri),txt=await rr.text();if(!rr.ok)throw new Error(`Remote actor ${rr.status}: ${txt.slice(0,500)}`);const remoteActor=JSON.parse(txt),pem=remoteActor.publicKey?.publicKeyPem;if(!pem)throw new Error('Remote actor has no public key');const key=await crypto.subtle.importKey('spki',ub64(pem.replace(/-----BEGIN PUBLIC KEY-----|-----END PUBLIC KEY-----|\s/g,'')),{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['verify']);const u=new URL(req.url),lines:string[]=[];for(const h of (p.headers||'(request-target) host date digest').split(' ')){if(h==='(request-target)')lines.push(`(request-target): ${req.method.toLowerCase()} ${u.pathname}${u.search}`);else if(h==='host')lines.push(`host: ${u.host}`);else if(h==='date')lines.push(`date: ${date}`);else if(h==='digest')lines.push(`digest: ${digest}`);else lines.push(`${h}: ${req.headers.get(h)||''}`)}const ok=await crypto.subtle.verify('RSASSA-PKCS1-v1_5',key,ub64(p.signature),new TextEncoder().encode(lines.join('\n')));if(!ok)throw new Error('Invalid ActivityPub HTTP signature');return {remoteActorUri,remoteActor}}
async function persistObject(e:any,activity:any,remoteActorUri:string){const object=activity.object&&typeof activity.object==='object'?activity.object:null;const objectUrl=typeof object?.id==='string'?object.id:(typeof activity.object==='string'?activity.object:'');if(!objectUrl)throw new Error('Create object id required');const attributed=typeof object?.attributedTo==='string'?object.attributedTo:(object?.attributedTo?.id||remoteActorUri);await db(e,'federation_objects?on_conflict=object_url',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({object_url:objectUrl,actor_url:attributed,object_type:object?.type||'Object',object:object||{id:objectUrl},published_at:object?.published?new Date(object.published).toISOString():null,fetched_at:new Date().toISOString(),updated_at:new Date().toISOString()})});return objectUrl}
async function processRelationshipDecision(e:any,activity:any,remoteActorUri:string){const followId=typeof activity.object==='string'?activity.object:activity.object?.id;if(!followId)throw new Error('Accept/Reject object id required');const rows=await db(e,`federation_relationships?activity_id=eq.${enc(followId)}&select=id,user_id,local_user_id,remote_actor_url,remote_actor_uri,relationship,state&limit=1`).then(r=>r.json() as Promise<any[]>);const row=rows[0];if(!row)return {matched:false};const expectedRemote=row.remote_actor_url||row.remote_actor_uri;if(expectedRemote&&expectedRemote!==remoteActorUri)throw new Error('Accept/Reject actor does not match the followed remote actor');const next=activity.type==='Accept'?'accepted':'rejected';await db(e,`federation_relationships?activity_id=eq.${enc(followId)}`,{method:'PATCH',body:JSON.stringify({relationship:next,state:next,last_error:null,updated_at:new Date().toISOString()})});return {matched:true,relationship:next,followId}}
export async function handleFederationInteraction(req:Request,e:any,username:string){if(req.method!=='POST')return null;const local=await actor(e,username);if(!local)return ap({error:'actor not found'},404);const body=await req.text();let activity:any;let activityId='';try{const verified=await verify(e,req,body,local);activity=JSON.parse(body);activityId=String(activity.id||'');if(!activityId)return ap({error:'activity id required'},400);await db(e,'federation_inbox',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({activity_id:activityId,activity_type:String(activity.type||'Unknown'),actor_url:verified.remoteActorUri,payload:activity,processing_status:'received',received_at:new Date().toISOString()})}).catch(async err=>{if(String(err).includes('409'))return;throw err});
if(activity.type==='Create'){const objectUrl=await persistObject(e,activity,verified.remoteActorUri);await db(e,`federation_inbox?activity_id=eq.${enc(activityId)}`,{method:'PATCH',body:JSON.stringify({processing_status:'processed',processed_at:new Date().toISOString(),error:null})});return ap({ok:true,received:true,storedObject:objectUrl},202)}
if(activity.type==='Like'||activity.type==='Announce'){const objectUrl=typeof activity.object==='string'?activity.object:activity.object?.id;if(!objectUrl)throw new Error(`${activity.type} object id required`);await db(e,'federation_remote_engagements',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({activity_uri:activityId,object_url:objectUrl,remote_actor_url:verified.remoteActorUri,interaction_type:activity.type==='Like'?'like':'repost',payload:activity,status:'active',received_at:new Date().toISOString(),updated_at:new Date().toISOString(),expires_at:new Date(Date.now()+30*86400000).toISOString()})});await db(e,`federation_inbox?activity_id=eq.${enc(activityId)}`,{method:'PATCH',body:JSON.stringify({processing_status:'processed',processed_at:new Date().toISOString(),error:null})});return ap({ok:true,received:true,engagementStored:true},202)}
if(activity.type==='Undo'){const target=typeof activity.object==='string'?activity.object:activity.object?.id;if(target)await db(e,`federation_remote_engagements?activity_uri=eq.${enc(target)}`,{method:'PATCH',body:JSON.stringify({status:'undone',updated_at:new Date().toISOString()})});await db(e,`federation_inbox?activity_id=eq.${enc(activityId)}`,{method:'PATCH',body:JSON.stringify({processing_status:'processed',processed_at:new Date().toISOString(),error:null})});return ap({ok:true,received:true,undone:Boolean(target)},202)}
if(activity.type==='Accept'||activity.type==='Reject'){const decision=await processRelationshipDecision(e,activity,verified.remoteActorUri);await db(e,`federation_inbox?activity_id=eq.${enc(activityId)}`,{method:'PATCH',body:JSON.stringify({processing_status:'processed',processed_at:new Date().toISOString(),error:null})});return ap({ok:true,received:true,relationshipMatched:decision.matched,relationship:decision.relationship||null},202)}
return null}catch(error){if(activityId)await db(e,`federation_inbox?activity_id=eq.${enc(activityId)}`,{method:'PATCH',body:JSON.stringify({processing_status:'failed',error:error instanceof Error?error.message:'Inbox processing failed'})}).catch(()=>{});return ap({error:error instanceof Error?error.message:'Inbox processing failed'},401)}}