import worker from './index';
interface Env { SUPABASE_URL:string; SUPABASE_PROJECT_REF:string; SUPABASE_ANON_KEY:string; SUPABASE_SECRET_KEY:string; SUPABASE_JWKS_URL:string; APP_ORIGIN:string; MEDIA:R2Bucket }
const DOMAIN='testagram-api.nahashonnyaga794.workers.dev'; const ORIGIN=`https://${DOMAIN}`; const AP='application/ld+json; profile="https://www.w3.org/ns/activitystreams", application/activity+json'; const CTX=['https://www.w3.org/ns/activitystreams','https://w3id.org/security/v1'];
const enc=(s:string)=>encodeURIComponent(s); const b64=(x:ArrayBuffer|Uint8Array)=>btoa(String.fromCharCode(...new Uint8Array(x))); const ub64=(s:string)=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
function json(body:unknown,status=200,h:HeadersInit={}){return new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...h}})}
function ap(body:unknown,status=200){return json(body,status,{'Content-Type':'application/activity+json; charset=utf-8','Access-Control-Allow-Origin':'*'})}
async function db(e:Env,path:string,init:RequestInit={}){const h=new Headers(init.headers);h.set('apikey',e.SUPABASE_SECRET_KEY);h.set('Authorization',`Bearer ${e.SUPABASE_SECRET_KEY}`);h.set('Content-Type','application/json');const r=await fetch(`${e.SUPABASE_URL}/rest/v1/${path}`,{...init,headers:h});if(!r.ok)throw new Error(`db ${r.status}: ${(await r.text()).slice(0,500)}`);return r}
async function actor(e:Env,u:string){const r=await db(e,`federation_actors?username=eq.${enc(u)}&select=*`);return (await r.json() as any[])[0]||null}
async function signedGet(local:any,url:string){const u=new URL(url),date=new Date().toUTCString(),key=await crypto.subtle.importKey('jwk',local.private_key_jwk,{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign']),canon=`(request-target): get ${u.pathname}${u.search}\nhost: ${u.host}\ndate: ${date}`,sig=await crypto.subtle.sign('RSASSA-PKCS1-v1_5',key,new TextEncoder().encode(canon));return fetch(url,{headers:{Date:date,Accept:AP,Signature:`keyId="${local.actor_url}#main-key",algorithm="rsa-sha256",headers="(request-target) host date",signature="${b64(sig)}"`,'User-Agent':'Testagram-Federation/1.5'}})}
async function remote(e:Env,local:any,url:string){const r=await signedGet(local,url),t=await r.text();if(!r.ok)throw new Error(`remote actor ${r.status}: ${t.slice(0,500)}`);return JSON.parse(t)}
function sigParts(v:string){const o:Record<string,string>={};for(const p of v.split(/,(?=\w+=)/)){const i=p.indexOf('=');if(i>0)o[p.slice(0,i).trim()]=p.slice(i+1).trim().replace(/^"|"$/g,'')}return o}
async function verify(e:Env,req:Request,body:string,local:any){const sh=req.headers.get('Signature'),date=req.headers.get('Date'),digest=req.headers.get('Digest');if(!sh||!date||!digest)throw new Error('Missing ActivityPub signature headers');const want=`sha-256=${b64(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(body)))}`;if(digest!==want&&digest!==want.replace('sha-256=','SHA-256='))throw new Error('Digest mismatch');const s=sigParts(sh);if(!s.keyId||!s.signature)throw new Error('Malformed ActivityPub signature');const ru=s.keyId.split('#')[0],ra=await remote(e,local,ru),pem=ra.publicKey?.publicKeyPem;if(!pem)throw new Error('Remote actor has no public key');const k=await crypto.subtle.importKey('spki',ub64(pem.replace(/-----BEGIN PUBLIC KEY-----|-----END PUBLIC KEY-----|\s/g,'')),{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['verify']),u=new URL(req.url),lines:string[]=[];for(const h of (s.headers||'(request-target) host date digest').split(' ')){if(h==='(request-target)')lines.push(`(request-target): ${req.method.toLowerCase()} ${u.pathname}${u.search}`);else if(h==='host')lines.push(`host: ${u.host}`);else if(h==='date')lines.push(`date: ${date}`);else if(h==='digest')lines.push(`digest: ${digest}`);else lines.push(`${h}: ${req.headers.get(h)||''}`)}if(!await crypto.subtle.verify('RSASSA-PKCS1-v1_5',k,ub64(s.signature),new TextEncoder().encode(lines.join('\n'))))throw new Error('Invalid ActivityPub HTTP signature');return ru}
async function webfinger(e:Env,req:Request){const r=new URL(req.url).searchParams.get('resource')||'',a=r.replace(/^acct:/,'').replace(/^@/,''),[u,d]=a.split('@');if(!u||d!==DOMAIN)return json({error:'actor not found'},404);const row=await actor(e,u);if(!row)return json({error:'actor not found'},404);const id=`${ORIGIN}/users/${enc(row.username)}`;return json({subject:`acct:${row.username}@${DOMAIN}`,aliases:[id],links:[{rel:'self',type:'application/activity+json',href:id}]})}
async function actorGet(e:Env,u:string){const row=await actor(e,u);if(!row)return ap({error:'actor not found'},404);const id=`${ORIGIN}/users/${enc(row.username)}`;return ap({'@context':CTX,id,type:'Person',preferredUsername:row.username,name:row.username,url:id,inbox:`${id}/inbox`,outbox:`${id}/outbox`,followers:`${id}/followers`,following:`${id}/following`,publicKey:{id:`${id}#main-key`,owner:id,publicKeyPem:row.public_key_pem},discoverable:true,indexable:true})}
async function inbox(e:Env,req:Request,u:string){if(req.method!=='POST')return ap({error:'ActivityPub inbox requires POST'},405);const local=await actor(e,u);if(!local)return ap({error:'actor not found'},404);const body=await req.text();try{const ra=await verify(e,req,body,local),a=JSON.parse(body);if(!a.id)return ap({error:'activity id required'},400);let dup=false;try{await db(e,'federation_inbox',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({activity_id:a.id,activity_type:a.type||'Unknown',actor_url:ra,payload:a,processing_status:'received',received_at:new Date().toISOString()})})}catch(x){if(String(x).includes('db 409'))dup=true;else throw x}if(['Accept','Reject','Undo'].includes(a.type)){const fid=typeof a.object==='string'?a.object:a.object?.id;if(fid){const rel=await db(e,`federation_relationships?activity_id=eq.${enc(fid)}&select=user_id,remote_actor_url`).then(r=>r.json() as Promise<any[]>);if(rel[0]){const relationship=a.type==='Accept'?'accepted':a.type==='Reject'?'rejected':'unfollowed';await db(e,`federation_relationships?user_id=eq.${enc(rel[0].user_id)}&remote_actor_url=eq.${enc(rel[0].remote_actor_url)}`,{method:'PATCH',body:JSON.stringify({relationship,updated_at:new Date().toISOString(),last_error:null})})}}}await db(e,`federation_inbox?activity_id=eq.${enc(a.id)}`,{method:'PATCH',body:JSON.stringify({processing_status:'processed',processed_at:new Date().toISOString()})});return ap({ok:true,duplicate:dup},202)}catch(x){return ap({error:x instanceof Error?x.message:'Inbox processing failed'},401)}}
async function nodeinfo(e:Env){const rows=await db(e,'federation_actors?select=user_id').then(r=>r.json() as Promise<any[]>).catch(()=>[]);return json({version:'2.1',software:{name:'Testagram',version:'1.0.0',repository:'https://github.com/Trendyzima/XClone-9b4dz1-9b4dz1-8936-20260809'},protocols:['activitypub'],usage:{users:{total:rows.length},localPosts:0,localComments:0},openRegistrations:true,metadata:{federation:true,domain:DOMAIN}})}
export default {async fetch(req:Request,e:Env,ctx:ExecutionContext){const u=new URL(req.url);if(u.pathname==='/api/health')return json({ok:true,service:'testagram-federation',federation:true,federationDomain:DOMAIN,database:'supabase',supabaseProjectRef:e.SUPABASE_PROJECT_REF,edge:'cloudflare'});if(u.pathname==='/.well-known/webfinger')return webfinger(e,req);if(u.pathname==='/.well-known/nodeinfo')return json({links:[{rel:'http://nodeinfo.diaspora.software/ns/schema/2.1',href:`${ORIGIN}/nodeinfo/2.1`} ]});if(u.pathname==='/.well-known/host-meta')return new Response(`<?xml version="1.0"?><XRD xmlns="http://docs.oasis-open.org/ns/xri/xrd-1.0"><Link rel="lrdd" type="application/xrd+xml" template="${ORIGIN}/.well-known/webfinger?resource={uri}"/></XRD>`,{headers:{'Content-Type':'application/xrd+xml; charset=utf-8'}});if(u.pathname==='/nodeinfo/2.1')return nodeinfo(e);const m=u.pathname.match(/^\/users\/([^/]+)(?:\/(inbox|outbox|followers|following))?$/);if(m){const name=decodeURIComponent(m[1]);if(m[2]==='inbox')return inbox(e,req,name);if(m[2])return ap({'@context':'https://www.w3.org/ns/activitystreams',id:`${ORIGIN}/users/${enc(name)}/${m[2]}`,type:m[2]==='outbox'?'OrderedCollection':'Collection',totalItems:0,orderedItems:[]});return actorGet(e,name)}return worker.fetch(req,e,ctx)}};
