import { ACTIVITY_CONTEXTS, actorKeyMatches, federationFetch, federationJson } from './federation-security.ts';
const now=()=>new Date().toISOString();
const text=(v:unknown)=>typeof v==='string'?v:'';
const uri=(v:unknown)=>typeof v==='string'?v:v&&typeof v==='object'?text((v as Record<string,unknown>).id):'';
const enc=(v:string)=>encodeURIComponent(v);
const b64=(x:ArrayBuffer|Uint8Array)=>btoa(String.fromCharCode(...new Uint8Array(x)));
function pemToBytes(pem:string){const b=pem.replace(/-----BEGIN PUBLIC KEY-----|-----END PUBLIC KEY-----|\s/g,'');return Uint8Array.from(atob(b),c=>c.charCodeAt(0));}
async function localActorForObject(admin:any,objectUri:string){const {data,error}=await admin.from('federated_actors').select('*').or(`uri.eq.${enc(objectUri)},actor_url.eq.${enc(objectUri)}`).limit(1).maybeSingle();if(error)throw error;return data||null;}
async function remoteActor(admin:any,actorUri:string){const a=await federationJson(actorUri);if(!actorKeyMatches(a,actorUri))throw new Error('remote actor identity or public key is invalid');const domain=new URL(actorUri).hostname.toLowerCase();await admin.from('federated_instances').upsert({domain,status:'active',last_seen_at:now(),updated_at:now()},{onConflict:'domain'});return a;}
async function signAndSend(local:any,inbox:string,activity:any){if(!local?.private_key_jwk)throw new Error('local actor has no private signing key');const body=JSON.stringify(activity),u=await (async()=>{const x=new URL(inbox);return x})();const date=new Date().toUTCString(),digest=`SHA-256=${b64(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(body)))}`,key=await crypto.subtle.importKey('jwk',local.private_key_jwk,{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign']),signing=`(request-target): post ${u.pathname}${u.search}\nhost: ${u.host}\ndate: ${date}\ndigest: ${digest}`,sig=b64(await crypto.subtle.sign('RSASSA-PKCS1-v1_5',key,new TextEncoder().encode(signing)));return federationFetch(inbox,{method:'POST',body,headers:{Date:date,Digest:digest,Host:u.host,Accept:'application/activity+json, application/ld+json','Content-Type':'application/activity+json',Signature:`keyId="${local.uri||local.actor_url}#main-key",algorithm="rsa-sha256",headers="(request-target) host date digest",signature="${sig}"`,'User-Agent':'Testagram-Federation/5.0'}})}
async function recordDelivery(admin:any,local:any,activity:any,inbox:string,response:Response|null,error?:string){const {data,error:insertError}=await admin.from('federated_activities').insert({uri:activity.id,activity_type:activity.type,actor_uri:local.uri||local.actor_url,object_uri:uri(activity.object)||null,target_uri:uri(activity.target)||null,raw_activity:activity,received_at:now(),processed_at:now(),processing_state:'processed',processing_attempts:0}).select('id').single();if(insertError&&insertError.code!=='23505')throw insertError;if(!data?.id)return;await admin.from('federation_deliveries').upsert({activity_id:data.id,target_inbox:inbox,instance_domain:new URL(inbox).hostname,status:response?.ok?'delivered':'retry',attempt_count:1,next_attempt_at:new Date(Date.now()+60000).toISOString(),last_attempt_at:now(),last_status_code:response?.status||null,last_error:error||null,delivered_at:response?.ok?now():null,activity_payload:activity},{onConflict:'activity_id,target_inbox'});}
async function acceptOrReject(admin:any,local:any,remoteActorUri:string,followActivity:any,accept:boolean){const remote=await remoteActor(admin,remoteActorUri),inbox=remote.endpoints?.sharedInbox||remote.inbox;if(typeof inbox!=='string')throw new Error('remote actor has no inbox');const activity={"@context":ACTIVITY_CONTEXTS,id:`${local.uri||local.actor_url}/activities/${crypto.randomUUID()}`,type:accept?'Accept':'Reject',actor:local.uri||local.actor_url,object:followActivity};try{const r=await signAndSend(local,inbox,activity);if(!r.ok)throw new Error(`remote inbox returned HTTP ${r.status}`);await recordDelivery(admin,local,activity,inbox,r);}catch(e){await recordDelivery(admin,local,activity,inbox,null,e instanceof Error?e.message:String(e));}}
export async function processActivity(admin:any,a:any,actorUri:string){const type=text(a.type),o=a.object,objectUri=uri(o),targetUri=uri(a.target);if(!a.id||!actorUri)throw new Error('activity id and actor are required');
if(type==='Follow'){if(!targetUri)throw new Error('Follow target is required');const local=await localActorForObject(admin,targetUri);if(!local)throw new Error('Follow target is not a local actor');const blocked=await admin.from('federated_relationships').select('id').eq('local_user_id',local.user_id).eq('remote_actor_uri',actorUri).eq('relationship','blocked').in('state',['active','accepted']).maybeSingle();const accept=!blocked.data;await admin.from('federated_relationships').upsert({local_user_id:local.user_id,remote_actor_uri:actorUri,relationship:'follower',state:accept?'active':'rejected',updated_at:now()},{onConflict:'local_user_id,remote_actor_uri,relationship'});await acceptOrReject(admin,local,actorUri,a,accept);return;}
if(type==='Accept'||type==='Reject'){const followed=uri(o);if(!followed)throw new Error('Accept/Reject missing original Follow');const {data:original}=await admin.from('federated_activities').select('raw_activity,activity_type,actor_uri').eq('uri',followed).maybeSingle();if(!original||original.activity_type!=='Follow')throw new Error('Accept/Reject does not reference a stored Follow');if(original.actor_uri!==(await localActorForObject(admin,uri((original.raw_activity as any).object)))?.uri)throw new Error('original Follow actor is not local');const local=await localActorForObject(admin,uri((original.raw_activity as any).object));if(!local)throw new Error('local Follow target not found');if(actorUri===local.uri)throw new Error('local actor cannot Accept/Reject its own Follow');await admin.from('federated_relationships').upsert({local_user_id:local.user_id,remote_actor_uri:actorUri,relationship:'following',state:type==='Accept'?'active':'rejected',updated_at:now()},{onConflict:'local_user_id,remote_actor_uri,relationship'});return;}
if(type==='Create'||type==='Update'){const obj=typeof o==='object'&&o?o:null;if(!obj||!uri(obj.id))throw new Error('Create/Update object is invalid');const id=uri(obj.id),attributed=uri(obj.attributedTo)||actorUri;if(attributed!==actorUri)throw new Error('signed actor does not own the object');const existing=await admin.from('federated_objects').select('actor_uri').eq('uri',id).maybeSingle();if(existing.data?.actor_uri&&existing.data.actor_uri!==actorUri)throw new Error('object ownership mismatch');const domain=new URL(actorUri).hostname.toLowerCase();const inst=await admin.from('federated_instances').select('id').eq('domain',domain).maybeSingle();await admin.from('federated_objects').upsert({uri:id,object_type:text(obj.type)||'Object',actor_uri:actorUri,instance_id:inst.data?.id||null,url:text(obj.url)||id,content:text(obj.content)||text(obj.name)||null,summary:text(obj.summary)||null,published_at:obj.published?new Date(obj.published).toISOString():null,updated_at:obj.updated?new Date(obj.updated).toISOString():now(),sensitive:Boolean(obj.sensitive),in_reply_to_uri:uri(obj.inReplyTo)||null,quote_uri:uri(obj.quote)||null,attachments:Array.isArray(obj.attachment)?obj.attachment:[],tags:Array.isArray(obj.tag)?obj.tag:[],raw_object:obj,tombstone:false,deleted_at:null},{onConflict:'uri'});return;}
if(type==='Like'||type==='Announce'){if(!objectUri||!/^https:\/\//i.test(objectUri))throw new Error('interaction target must be HTTPS');await admin.from('federated_interactions').upsert({activity_uri:a.id,activity_type:type,actor_uri:actorUri,object_uri:objectUri,active:true,raw_activity:a,updated_at:now()},{onConflict:'activity_uri'});return;}
if(type==='Undo'){if(!objectUri)throw new Error('Undo missing referenced activity');const {data:original}=await admin.from('federated_activities').select('activity_type,actor_uri,raw_activity').eq('uri',objectUri).maybeSingle();if(!original)throw new Error('Undo references an unknown activity');if(original.actor_uri!==actorUri)throw new Error('Undo actor does not own referenced activity');if(original.activity_type==='Follow'){const target=uri((original.raw_activity as any).object),local=await localActorForObject(admin,target);if(!local)throw new Error('Follow target is not local');await admin.from('federated_relationships').update({state:'removed',updated_at:now()}).eq('local_user_id',local.user_id).eq('remote_actor_uri',actorUri).eq('relationship','follower');}else if(original.activity_type==='Like'||original.activity_type==='Announce'){await admin.from('federated_interactions').update({active:false,updated_at:now()}).eq('activity_uri',objectUri);}else throw new Error('Undo type is unsupported');return;}
if(type==='Delete'){if(!objectUri)throw new Error('Delete missing object');const existing=await admin.from('federated_objects').select('actor_uri').eq('uri',objectUri).maybeSingle();if(!existing.data)throw new Error('cannot delete unknown federated object');if(existing.data.actor_uri!==actorUri)throw new Error('signed actor does not own deleted object');await admin.from('federated_objects').update({tombstone:true,deleted_at:now(),raw_object:{id:objectUri,type:'Tombstone',formerType:'Note'},updated_at:now()}).eq('uri',objectUri);return;}
throw new Error(`unsupported ActivityPub type: ${type}`);}
