const MAX_RESPONSE_BYTES=1_500_000;
const FETCH_TIMEOUT_MS=12_000;
const MAX_REDIRECTS=2;
const ACTIVITY_ACCEPT='application/activity+json, application/ld+json;q=0.9, application/json;q=0.5';

function ipv4Private(ip:string){const p=ip.split('.').map(Number);if(p.length!==4||p.some(n=>!Number.isInteger(n)||n<0||n>255))return true;const [a,b]=p;return a===0||a===10||a===127||(a===100&&b>=64&&b<=127)||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&b===0)||(a===192&&b===168)||(a===198&&(b===18||b===19))||a>=224;}
function ipv6Private(ip:string){const x=ip.toLowerCase().split('%')[0];if(x==='::'||x==='::1'||x.startsWith('fc')||x.startsWith('fd')||x.startsWith('fe8')||x.startsWith('fe9')||x.startsWith('fea')||x.startsWith('feb')||x.startsWith('ff'))return true;const mapped=x.match(/^::ffff:(\d+\.\d+\.\d+\.\d+)$/);return !!mapped&&ipv4Private(mapped[1]);}
function literalPrivate(host:string){const h=host.replace(/^\[|\]$/g,'');if(/^\d+\.\d+\.\d+\.\d+$/.test(h))return ipv4Private(h);if(h.includes(':'))return ipv6Private(h);return false;}
async function resolvePublic(host:string){if(literalPrivate(host))throw new Error('federation target resolves to a private or special address');if(host==='localhost'||host.endsWith('.localhost')||host.endsWith('.local')||host.endsWith('.internal'))throw new Error('federation target hostname is not public');const [a,aaaa]=await Promise.all([Deno.resolveDns(host,'A').catch(()=>[] as string[]),Deno.resolveDns(host,'AAAA').catch(()=>[] as string[])]);const ips=[...a,...aaaa];if(!ips.length)throw new Error('federation target DNS did not resolve');for(const ip of ips)if(ip.includes(':')?ipv6Private(ip):ipv4Private(ip))throw new Error('federation target resolves to a private or special address');}
export async function assertFederationUrl(input:string){let u:URL;try{u=new URL(input)}catch{throw new Error('invalid federation URL')}if(u.protocol!=='https:')throw new Error('federation URLs must use HTTPS');if(u.username||u.password)throw new Error('federation URL credentials are forbidden');await resolvePublic(u.hostname);return u;}
async function readLimited(r:Response){const len=Number(r.headers.get('content-length')||0);if(len>MAX_RESPONSE_BYTES)throw new Error('federation response too large');if(!r.body)return '';const reader=r.body.getReader();const chunks:Uint8Array[]=[];let total=0;try{while(true){const {done,value}=await reader.read();if(done)break;if(value){total+=value.byteLength;if(total>MAX_RESPONSE_BYTES)throw new Error('federation response too large');chunks.push(value)}}}finally{reader.releaseLock()}const out=new Uint8Array(total);let o=0;for(const c of chunks){out.set(c,o);o+=c.byteLength}return new TextDecoder().decode(out);}
export async function federationFetch(input:string,init:RequestInit={},redirects=0){const u=await assertFederationUrl(input);const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),FETCH_TIMEOUT_MS);try{const headers=new Headers(init.headers||{});if(!headers.has('Accept'))headers.set('Accept',ACTIVITY_ACCEPT);const r=await fetch(u.toString(),{...init,redirect:'manual',headers,signal:controller.signal});if(r.status>=300&&r.status<400){if(redirects>=MAX_REDIRECTS)throw new Error('too many federation redirects');const location=r.headers.get('location');if(!location)throw new Error('federation redirect missing location');const next=new URL(location,u).toString();return federationFetch(next,init,redirects+1)}return r;}catch(e){if(e instanceof DOMException&&e.name==='AbortError')throw new Error('federation request timed out');throw e}finally{clearTimeout(timer)}}
export async function federationJson(input:string,init:RequestInit={}){const r=await federationFetch(input,init);if(!r.ok)throw new Error(`federation fetch failed: ${r.status}`);const ct=(r.headers.get('content-type')||'').toLowerCase();if(ct&&!ct.includes('activity+json')&&!ct.includes('ld+json')&&!ct.includes('application/json'))throw new Error('unexpected federation content type');const raw=await readLimited(r);try{return JSON.parse(raw)}catch{throw new Error('invalid federation JSON')}}
export function actorKeyMatches(actor:any,actorUri:string){const id=typeof actor?.id==='string'?actor.id:'';const key=actor?.publicKey;return (actor?.type==='Person'||actor?.type==='Service'||actor?.type==='Organization'||actor?.type==='Group'||actor?.type==='Application')&&id===actorUri&&!!key&&typeof key.publicKeyPem==='string'&&key.publicKeyPem.includes('BEGIN PUBLIC KEY')&&(typeof key.id!=='string'||key.id.startsWith(actorUri+'#'));}
export const ACTIVITY_CONTEXTS=['https://www.w3.org/ns/activitystreams','https://w3id.org/security/v1'];
