import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;
const SERVICE_ROLE=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||Deno.env.get("SUPABASE_SECRET_KEY")!;
const ANON_KEY=Deno.env.get("SUPABASE_ANON_KEY")||Deno.env.get("SUPABASE_PUBLISHABLE_KEY")!;
const PAYPAL_CLIENT_ID=Deno.env.get("PAYPAL_CLIENT_ID");
const PAYPAL_CLIENT_SECRET=Deno.env.get("PAYPAL_CLIENT_SECRET");
const PAYPAL_MODE=(Deno.env.get("PAYPAL_MODE")||"sandbox").toLowerCase();
const PAYPAL_WEBHOOK_ID=Deno.env.get("PAYPAL_WEBHOOK_ID");
const APP_ORIGIN=Deno.env.get("APP_ORIGIN")||"https://testagram.site";
const PAYPAL_BASE=PAYPAL_MODE==="live"?"https://api-m.paypal.com":"https://api-m.sandbox.paypal.com";
const admin=createClient(SUPABASE_URL,SERVICE_ROLE,{auth:{persistSession:false,autoRefreshToken:false}});
const CORS={"Access-Control-Allow-Origin":APP_ORIGIN,"Access-Control-Allow-Headers":"authorization, apikey, content-type","Access-Control-Allow-Methods":"POST,OPTIONS"};
const json=(v:unknown,status=200)=>new Response(JSON.stringify(v),{status,headers:{...CORS,"Content-Type":"application/json","Cache-Control":"no-store"}});
function requirePaypalConfig(){if(!PAYPAL_CLIENT_ID||!PAYPAL_CLIENT_SECRET)throw new Error("PayPal server credentials are not configured")}
async function paypalToken(){requirePaypalConfig();const basic=btoa(`${PAYPAL_CLIENT_ID}:${PAYPAL_CLIENT_SECRET}`);const r=await fetch(`${PAYPAL_BASE}/v1/oauth2/token`,{method:"POST",headers:{Authorization:`Basic ${basic}`,"Content-Type":"application/x-www-form-urlencoded",Accept:"application/json"},body:"grant_type=client_credentials"});const b=await r.json().catch(()=>({}));if(!r.ok||!b.access_token)throw new Error(`PayPal OAuth failed (${r.status})`);return b.access_token as string}
async function paypal(path:string,init:RequestInit={}){const token=await paypalToken();const headers=new Headers(init.headers);headers.set("Authorization",`Bearer ${token}`);headers.set("Content-Type","application/json");headers.set("Accept","application/json");const r=await fetch(`${PAYPAL_BASE}${path}`,{...init,headers});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`PayPal API ${r.status}: ${JSON.stringify(b).slice(0,1200)}`);return b}
async function authenticatedUser(req:Request){const auth=req.headers.get("Authorization")||"";const token=auth.replace(/^Bearer\s+/i,"").trim();if(!token)throw new Error("Authentication required");const client=createClient(SUPABASE_URL,ANON_KEY,{global:{headers:{Authorization:`Bearer ${token}`}},auth:{persistSession:false,autoRefreshToken:false}});const {data:{user},error}=await client.auth.getUser(token);if(error||!user)throw new Error("Invalid authentication");return user}
function money(v:unknown){const n=Number(v);if(!Number.isFinite(n)||n<=0||n>10000)throw new Error("Amount must be between 0 and 10,000");return n.toFixed(2)}
async function createOrder(userId:string,amount:string,currency:string){const order=await paypal("/v2/checkout/orders",{method:"POST",headers:{"PayPal-Request-Id":crypto.randomUUID(),Prefer:"return=representation"},body:JSON.stringify({intent:"CAPTURE",purchase_units:[{reference_id:`wallet-${userId}`,custom_id:userId,description:"Testagram wallet deposit",amount:{currency_code:currency,value:amount}}],application_context:{brand_name:"Testagram",user_action:"PAY_NOW",return_url:`${APP_ORIGIN}/wallet?paypal=success`,cancel_url:`${APP_ORIGIN}/wallet?paypal=cancel`}})});const approval=(order.links||[]).find((l:any)=>l.rel==="approve")?.href||null;await admin.from("paypal_orders").insert({user_id:userId,paypal_order_id:order.id,amount,currency,status:"created",approval_url:approval});return {orderId:order.id,status:order.status,approvalUrl:approval}}
function captureDetails(order:any){const capture=order?.purchase_units?.[0]?.payments?.captures?.[0];return {id:capture?.id as string|undefined,status:capture?.status as string|undefined,amount:capture?.amount?.value as string|undefined,currency:capture?.amount?.currency_code as string|undefined}}
async function captureOrder(userId:string,orderId:string){const {data:registered,error:lookupError}=await admin.from("paypal_orders").select("*").eq("paypal_order_id",orderId).eq("user_id",userId).maybeSingle();if(lookupError||!registered)throw new Error("PayPal order not registered for this account");if(registered.status==="captured")return {ok:true,alreadyCaptured:true,wallet:(await admin.rpc("ensure_wallet_account",{p_user_id:userId})).data};const order=await paypal(`/v2/checkout/orders/${encodeURIComponent(orderId)}/capture`,{method:"POST",headers:{"PayPal-Request-Id":crypto.randomUUID()},body:"{}"});const d=captureDetails(order);if(order.status!=="COMPLETED"||d.status!=="COMPLETED"||!d.id||!d.amount||!d.currency)throw new Error("PayPal did not return a completed capture");if(Number(d.amount).toFixed(2)!==Number(registered.amount).toFixed(2)||d.currency!==registered.currency)throw new Error("Captured PayPal amount does not match the registered wallet deposit");const {data:wallet,error}=await admin.rpc("credit_wallet_paypal",{p_user_id:userId,p_paypal_order_id:orderId,p_paypal_capture_id:d.id,p_amount:d.amount,p_currency:d.currency,p_metadata:{source:"paypal_capture",order_status:order.status}});if(error)throw new Error(error.message);return {ok:true,alreadyCaptured:false,wallet,captureId:d.id}}
async function verifyWebhook(req:Request,raw:string){requirePaypalConfig();if(!PAYPAL_WEBHOOK_ID)throw new Error("PAYPAL_WEBHOOK_ID is not configured");const h=(name:string)=>req.headers.get(name)||"";const verification=await paypal("/v1/notifications/verify-webhook-signature",{method:"POST",body:JSON.stringify({auth_algo:h("PAYPAL-AUTH-ALGO"),cert_url:h("PAYPAL-CERT-URL"),transmission_id:h("PAYPAL-TRANSMISSION-ID"),transmission_sig:h("PAYPAL-TRANSMISSION-SIG"),transmission_time:h("PAYPAL-TRANSMISSION-TIME"),webhook_id:PAYPAL_WEBHOOK_ID,webhook_event:JSON.parse(raw)})});return verification.verification_status==="SUCCESS"}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:CORS});if(req.method!=="POST")return json({error:"Method not allowed"},405);try{const bodyText=await req.text();const body=bodyText?JSON.parse(bodyText):{};const action=String(body.action||"health");if(action==="health")return json({ok:true,service:"wallet-paypal",paypalMode:PAYPAL_MODE,configured:Boolean(PAYPAL_CLIENT_ID&&PAYPAL_CLIENT_SECRET)});if(action==="webhook"){const valid=await verifyWebhook(req,bodyText);if(!valid)return json({error:"Invalid PayPal webhook signature"},401);const event=body;const orderId=event?.resource?.supplementary_data?.related_ids?.order_id;if(event.event_type==="PAYMENT.CAPTURE.COMPLETED"&&orderId){const {data:registered}=await admin.from("paypal_orders").select("user_id,amount,currency,status").eq("paypal_order_id",orderId).maybeSingle();const captureId=event?.resource?.id;const amount=event?.resource?.amount?.value;const currency=event?.resource?.amount?.currency_code;if(registered&&registered.status!=="captured"&&captureId&&amount&&currency)await admin.rpc("credit_wallet_paypal",{p_user_id:registered.user_id,p_paypal_order_id:orderId,p_paypal_capture_id:captureId,p_amount:amount,p_currency:currency,p_metadata:{source:"paypal_webhook",event_id:event.id,event_type:event.event_type}})}return json({ok:true})}const user=await authenticatedUser(req);if(action==="wallet"){const {data:wallet,error}=await admin.rpc("ensure_wallet_account",{p_user_id:user.id});if(error)throw new Error(error.message);const {data:profile}=await admin.from("profiles").select("username,display_name,avatar_url,verified").eq("id",user.id).maybeSingle();const {data:transactions}=await admin.from("wallet_transactions").select("id,type,direction,amount,currency,status,provider,description,created_at").eq("user_id",user.id).order("created_at",{ascending:false}).limit(50);return json({ok:true,wallet,profile,transactions:transactions||[]})}if(action==="create_order"){const currency=String(body.currency||"USD").toUpperCase();if(!["USD","EUR","GBP"].includes(currency))throw new Error("PayPal wallet deposits currently support USD, EUR and GBP");return json(await createOrder(user.id,money(body.amount),currency),201)}if(action==="capture_order"){const orderId=String(body.orderId||"");if(!orderId)throw new Error("orderId is required");return json(await captureOrder(user.id,orderId))}return json({error:"Unknown action"},400)}catch(e){console.error("[wallet-paypal]",e);return json({error:e instanceof Error?e.message:"Wallet service error"},400)}});
