import { useEffect, useMemo, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { ArrowLeft, Globe, Loader2, UserPlus, UserMinus } from 'lucide-react';
import { TopBar } from '@/components/layout/TopBar';
import { useAuth } from '@/hooks/useAuth';
import { supabase } from '@/lib/supabase';
import * as federation from '@/api/federation';
import * as localFediverse from '@/api/federatedLocal';
import { FederatedPostCard } from '@/components/features/FederatedPostCard';
import { toast } from 'sonner';

function firstHttp(...values: unknown[]): string { return values.find(v => typeof v === 'string' && /^https?:\/\//i.test(v.trim())) as string || ''; }
function actorUrlOf(actor: any): string { return firstHttp(actor?.url, actor?.id, actor?.actor_url, actor?.uri); }
function actorDomain(actor: any, fallback = '') { try { return new URL(actorUrlOf(actor)).hostname; } catch { return fallback; } }
function actorHandle(actor: any, fallbackDomain = '') { const acct = String(actor?.acct ?? actor?.preferredUsername ?? actor?.username ?? 'unknown').replace(/^@/, ''); if (acct.includes('@')) return acct; const domain = actorDomain(actor, fallbackDomain); return domain ? `${acct}@${domain}` : acct; }
function mergeActor(value: any, fallback: string): any { const c = [value?.actor, value?.account, value?.author, value?.remote_accounts, value?.remote_account, value?.raw_object?.attributedTo, value].filter(Boolean); const merged = Object.assign({}, ...c.reverse(), ...c); if (!merged.id && !merged.url) merged.id = fallback; return merged; }

export default function FediverseProfilePage() {
  const location = useLocation(); const navigate = useNavigate(); const { user } = useAuth();
  const [actor, setActor] = useState<any>(null); const [posts, setPosts] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [following, setFollowing] = useState(false); const [busy, setBusy] = useState(false);
  const actorTarget = useMemo(() => new URLSearchParams(location.search).get('actor')?.trim() ?? '', [location.search]);
  const canonicalActor = actorUrlOf(actor) || actorTarget; const domain = actorDomain(actor, actorTarget.includes('@') ? actorTarget.split('@').pop() || '' : ''); const username = actor?.preferredUsername ?? actor?.username ?? actorTarget.replace(/^@/, '').split('@')[0] ?? 'unknown'; const displayName = actor?.name ?? actor?.display_name ?? username; const avatar = actor?.icon?.url ?? actor?.icon?.href ?? actor?.avatar_url ?? actor?.avatar; const bio = actor?.summary ?? actor?.bio ?? '';

  useEffect(() => { let alive = true; (async () => { if (!actorTarget) { setLoading(false); return; } setLoading(true); try { const resolved = await federation.getUser(actorTarget); const remote = mergeActor(resolved?.actor ?? resolved, actorTarget); if (!alive) return; setActor(remote); const candidates = [...new Set([actorUrlOf(remote), actorTarget].filter(Boolean))]; const rows: any[] = []; for (const candidate of candidates) { const { data, error } = await supabase.from('remote_posts').select('*, remote_accounts(*)').eq('actor_url', candidate).order('published_at', { ascending: false }).limit(50); if (!error && data) rows.push(...data); } setPosts([...new Map(rows.map(row => [String(row.object_url ?? row.uri ?? row.url ?? row.id), row])).values()]); if (user) setFollowing(await localFediverse.isLocallyFollowing(user.id, actorUrlOf(remote) || actorTarget)); } catch (e: any) { if (alive) toast.error(e?.message ?? 'Unable to load this Fediverse profile inside Testagram.'); } finally { if (alive) setLoading(false); } })(); return () => { alive = false; }; }, [actorTarget, user?.id]);

  const ensureAuth = () => { if (!user) { navigate('/auth'); return false; } return true; };
  const toggleFollow = async () => { if (!ensureAuth() || !canonicalActor || busy) return; setBusy(true); try { await localFediverse.setLocalFollow(user!.id, canonicalActor, actorHandle(actor, domain), !following); setFollowing(v => !v); toast.success(following ? 'Unfollowed locally' : 'Following locally'); } catch (e: any) { toast.error(e?.message ?? 'Unable to update local follow state'); } finally { setBusy(false); } };

  return <div className="min-h-screen bg-background pb-20"><TopBar title="Fediverse profile" showBack /><div className="p-4 border-b border-border"><button onClick={() => navigate(-1)} className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground mb-4"><ArrowLeft className="w-4 h-4" />Back</button>{loading ? <div className="py-12 flex justify-center"><Loader2 className="w-7 h-7 animate-spin text-primary" /></div> : <><div className="flex items-start gap-4"><div className="w-20 h-20 rounded-full bg-muted overflow-hidden shrink-0">{avatar ? <img src={avatar} alt="" className="w-full h-full object-cover" /> : <div className="w-full h-full flex items-center justify-center text-2xl font-bold">{String(displayName)[0]?.toUpperCase()}</div>}</div><div className="min-w-0 flex-1"><h1 className="text-xl font-bold truncate">{displayName}</h1><p className="text-sm text-muted-foreground truncate">@{actorHandle(actor, domain)}</p><p className="text-xs text-purple-500 flex items-center gap-1 mt-1"><Globe className="w-3 h-3" />Fediverse · {domain || 'remote actor'}</p></div>{canonicalActor && <button onClick={toggleFollow} disabled={busy} aria-pressed={following} className={`shrink-0 inline-flex items-center gap-1.5 px-3 py-2 rounded-full text-sm font-semibold ${following ? 'border border-border text-muted-foreground' : 'bg-primary text-primary-foreground'}`}>{busy ? <Loader2 className="w-4 h-4 animate-spin" /> : following ? <UserMinus className="w-4 h-4" /> : <UserPlus className="w-4 h-4" />}{following ? 'Following' : 'Follow'}</button>}</div>{bio && <div className="mt-4 text-sm leading-relaxed" dangerouslySetInnerHTML={{ __html: bio }} />}</>}</div><div className="divide-y divide-border">{posts.map((post, index) => <FederatedPostCard key={String(post.object_url ?? post.uri ?? post.url ?? post.id ?? index)} post={post} />)}</div>{!loading && !posts.length && <div className="p-10 text-center text-muted-foreground text-sm">No cached posts are available for this profile yet.</div>}</div>;
}
