import { useEffect, useMemo, useState } from 'react';
import { useLocation, useNavigate, useSearchParams } from 'react-router-dom';
import { ArrowLeft, Globe, Loader2 } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import * as federation from '@/api/federation';
import { FederatedPostCard } from '@/components/features/FederatedPostCard';
import { useSEO } from '@/hooks/useSEO';

const values = (...xs: unknown[]) => [...new Set(xs.flatMap(x => typeof x === 'string' && x.trim() ? [x.trim()] : []))];
const http = (x: unknown): x is string => typeof x === 'string' && /^https?:\/\//i.test(x.trim());
const unwrap = (x: any): any[] => Array.isArray(x) ? x : [x?.items, x?.posts, x?.statuses, x?.data?.items, x?.data?.posts, x?.data?.statuses, x?.data].find(Array.isArray) ?? [];
const clean = (x: string) => { try { return decodeURIComponent(x).replace(/\/+$/, '').trim(); } catch { return x.replace(/\/+$/, '').trim(); } };

function normalizePost(value: any) { if (!value) return null; const raw = value.raw_object ?? value.object ?? value.activity ?? {}; const account = value.actor ?? value.account ?? value.author ?? value.remote_accounts ?? raw.attributedTo ?? {}; const objectUrl = values(value.object_url, value.canonical_url, value.uri, value.url, raw.id, raw.url).find(http) ?? ''; const actorUrl = values(account.url, account.id, value.actor_url, value.actor_uri, raw.attributedTo?.url, raw.attributedTo?.id).find(http) ?? ''; return { ...raw, ...value, actor: { ...account, url: actorUrl || account.url, id: actorUrl || account.id, preferredUsername: account.preferredUsername ?? account.username ?? value.actor_username, name: account.name ?? account.display_name ?? value.actor_name, icon: account.icon ?? (account.avatar_url ? { url: account.avatar_url } : undefined) }, id: objectUrl || value.id, object_url: objectUrl || value.object_url || value.uri || value.url, url: objectUrl || value.url, uri: objectUrl || value.uri, content: value.content ?? raw.content ?? value.text ?? raw.text ?? '', created_at: value.created_at ?? value.published_at ?? raw.published ?? raw.created_at ?? '', media_attachments: value.media_attachments ?? raw.media_attachments ?? value.attachments ?? [] }; }
function matches(row: any, candidates: string[]) { const raw = row?.raw_object ?? row?.object ?? row?.activity ?? {}; const ids = values(row?.id, row?.uri, row?.url, row?.object_url, row?.canonical_url, raw?.id, raw?.url).map(clean); return candidates.some(candidate => ids.includes(clean(candidate))); }
async function findCached(candidates: string[]) { for (const table of ['remote_posts', 'federation_objects', 'federated_objects']) { const { data, error } = await supabase.from(table).select('*').limit(500); if (!error && data?.length) { const hit = data.find(row => matches(row, candidates)); if (hit) return hit; } } return null; }

export default function FediversePostPage() { const location = useLocation(); const navigate = useNavigate(); const [params] = useSearchParams(); const [post, setPost] = useState<any>(() => normalizePost(location.state?.post)); const [loading, setLoading] = useState(!post); const [error, setError] = useState(''); const objectUrl = useMemo(() => params.get('url') || post?.object_url || post?.url || post?.uri || '', [params, post]); useSEO({ title: post ? `${post.actor?.name ?? post.actor?.preferredUsername ?? 'Fediverse post'} on Testagram` : 'Fediverse post — Testagram', description: 'View a Fediverse post inside Testagram.', url: `/fediverse/post?url=${encodeURIComponent(objectUrl)}`, type: 'article' }); useEffect(() => { if (!objectUrl || post) { if (post) setLoading(false); return; } let cancelled = false; (async () => { try { const candidates = values(objectUrl, clean(objectUrl)); let found = await findCached(candidates); if (!found) { const timeline = await federation.getFederatedTimeline({ limit: 200 }); found = unwrap(timeline).find(item => matches(item, candidates)); } if (!found) throw new Error('This Fediverse post is not cached locally yet.'); if (!cancelled) setPost(normalizePost(found)); } catch (e) { if (!cancelled) setError(e instanceof Error ? e.message : 'Unable to load this Fediverse post locally.'); } finally { if (!cancelled) setLoading(false); } })(); return () => { cancelled = true; }; }, [objectUrl, post]); if (loading) return <div className="min-h-screen bg-background flex items-center justify-center"><Loader2 className="w-8 h-8 animate-spin text-primary" /></div>; if (!post) return <div className="min-h-screen bg-background p-8 text-center"><Globe className="w-12 h-12 mx-auto mb-3 opacity-30" /><p className="font-semibold">Unable to open this post in Testagram</p><p className="text-sm mt-1">{error || 'The Fediverse object is not available in the local cache.'}</p><button onClick={() => navigate('/fediverse')} className="mt-5 px-4 py-2 rounded-full bg-primary text-primary-foreground text-sm font-semibold">Back to Fediverse</button></div>; return <div className="min-h-screen bg-background pb-20"><div className="sticky top-0 z-20 bg-background/95 backdrop-blur border-b border-border p-3 flex items-center gap-3"><button onClick={() => navigate(-1)} className="p-2 rounded-full hover:bg-muted" aria-label="Go back"><ArrowLeft className="w-5 h-5" /></button><div><h1 className="font-bold">Post</h1><p className="text-[11px] text-muted-foreground flex items-center gap-1"><Globe className="w-3 h-3" />Fediverse · viewed locally in Testagram</p></div></div><FederatedPostCard post={post} disableNavigation /></div>; }
