import { useCallback, useEffect, useRef, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { Bookmark, Heart, Loader2, MessageCircle, Pause, Play, Search, Share2, Volume2, VolumeX, X } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/hooks/useAuth';
import { formatNumber } from '@/lib/utils';
import { toast } from 'sonner';

type Reel = { id:string; content:string|null; video_url:string|null; image_url:string|null; likes_count:number; replies_count:number; views_count:number; created_at:string; user_id:string; user_profiles?:{username:string;avatar_url:string|null;verified:boolean} };
const PAGE_SIZE=10;

function ReelCard({ reel, active, muted, onMute, liked, onLike, saved, onSave, onComment, onShare }:{reel:Reel;active:boolean;muted:boolean;onMute:()=>void;liked:boolean;onLike:()=>void;saved:boolean;onSave:()=>void;onComment:()=>void;onShare:()=>void}) {
 const videoRef=useRef<HTMLVideoElement>(null); const [playing,setPlaying]=useState(false); const [progress,setProgress]=useState(0);
 useEffect(()=>{const video=videoRef.current;if(!video)return;video.muted=muted;if(active){video.play().then(()=>setPlaying(true)).catch(()=>setPlaying(false));}else{video.pause();video.currentTime=0;setPlaying(false);setProgress(0);}},[active,muted]);
 return <section className="relative h-[100svh] w-full snap-start snap-always bg-black overflow-hidden"><video ref={videoRef} src={reel.video_url??undefined} poster={reel.image_url??undefined} playsInline loop muted={muted} preload={active?'auto':'metadata'} onTimeUpdate={e=>{const v=e.currentTarget;setProgress(v.duration?Math.min(100,v.currentTime/v.duration*100):0)}} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onError={()=>toast.error('This reel could not be played')} className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-black/90 via-transparent to-black/25 pointer-events-none"/>
 <button aria-label={playing?'Pause reel':'Play reel'} onClick={()=>{const v=videoRef.current;if(!v)return;if(v.paused)v.play().then(()=>setPlaying(true));else{v.pause();setPlaying(false)}}} className="absolute inset-0 m-auto w-16 h-16 rounded-full bg-black/35 flex items-center justify-center text-white">{playing?<Pause className="w-7 h-7 opacity-0 hover:opacity-100" fill="white"/>:<Play className="w-7 h-7 ml-1" fill="white"/>}</button>
 <div className="absolute left-4 right-20 bottom-7 text-white"><div className="font-bold text-sm mb-2">@{reel.user_profiles?.username??'creator'}</div>{reel.content&&<p className="text-sm leading-5 line-clamp-3">{reel.content}</p>}</div>
 <div className="absolute right-3 bottom-7 flex flex-col items-center gap-4 text-white"><button aria-label="Like" onClick={onLike} className="flex flex-col items-center"><Heart className={`w-7 h-7 ${liked?'fill-red-500 text-red-500':''}`}/><span className="text-[11px]">{formatNumber(reel.likes_count)}</span></button><button aria-label="Comments" onClick={onComment} className="flex flex-col items-center"><MessageCircle className="w-7 h-7"/><span className="text-[11px]">{formatNumber(reel.replies_count)}</span></button><button aria-label="Share" onClick={onShare}><Share2 className="w-7 h-7"/></button><button aria-label="Save" onClick={onSave}><Bookmark className={`w-7 h-7 ${saved?'fill-white':''}`}/></button><button aria-label="Mute" onClick={onMute} className="w-10 h-10 rounded-full bg-black/40 flex items-center justify-center">{muted?<VolumeX className="w-5 h-5"/>:<Volume2 className="w-5 h-5"/>}</button></div><div className="absolute bottom-0 left-0 right-0 h-0.5 bg-white/15"><div className="h-full bg-white" style={{width:`${progress}%`}}/></div></section>;
}

export default function ReelsPage(){
 const navigate=useNavigate(); const {user}=useAuth(); const [params,setParams]=useSearchParams(); const start=params.get('start'); const root=useRef<HTMLDivElement>(null); const [reels,setReels]=useState<Reel[]>([]); const [active,setActive]=useState(0); const [loading,setLoading]=useState(true); const [hasMore,setHasMore]=useState(true); const [page,setPage]=useState(0); const [muted,setMuted]=useState(true); const [liked,setLiked]=useState<string[]>([]); const [saved,setSaved]=useState<string[]>([]); const [search,setSearch]=useState('');
 const load=useCallback(async(p:number)=>{setLoading(true);let q=supabase.from('posts').select('id,content,video_url,image_url,likes_count,replies_count,views_count,created_at,user_id,user_profiles(username,avatar_url,verified)').eq('is_video',true).not('video_url','is',null).order('created_at',{ascending:false}).range(p*PAGE_SIZE,(p+1)*PAGE_SIZE-1);if(search.trim())q=q.ilike('content',`%${search.trim()}%`);const {data,error}=await q;if(error){toast.error('Could not load reels');setLoading(false);return;}let rows=(data??[]) as unknown as Reel[];
 if(p===0&&start){const selected=rows.find(r=>r.video_url===start);if(selected)rows=[selected,...rows.filter(r=>r.id!==selected.id)];else{const exact=await supabase.from('posts').select('id,content,video_url,image_url,likes_count,replies_count,views_count,created_at,user_id,user_profiles(username,avatar_url,verified)').eq('is_video',true).eq('video_url',start).maybeSingle();if(exact.data)rows=[exact.data as unknown as Reel,...rows.filter(r=>r.id!==exact.data.id)];}}
 setHasMore(rows.length>=PAGE_SIZE);setReels(prev=>p===0?rows:[...prev,...rows]);setPage(p);setLoading(false);},[search,start]);
 useEffect(()=>{void load(0)},[load]);
 useEffect(()=>{if(!user)return;Promise.all([supabase.from('post_likes').select('post_id').eq('user_id',user.id).limit(500),supabase.from('bookmarks').select('post_id').eq('user_id',user.id).limit(500)]).then(([a,b])=>{setLiked((a.data??[]).map((x:any)=>x.post_id));setSaved((b.data??[]).map((x:any)=>x.post_id))})},[user?.id]);
 useEffect(()=>{const r=root.current;if(!r)return;const obs=new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting||entry.intersectionRatio<.7)return;const index=Number((entry.target as HTMLElement).dataset.index);setActive(index);if(index>=reels.length-3&&hasMore&&!loading)void load(page+1);}),{root:r,threshold:[.7]});r.querySelectorAll<HTMLElement>('[data-index]').forEach(el=>obs.observe(el));return()=>obs.disconnect()},[reels.length,hasMore,loading,page,load]);
 const like=async(reel:Reel)=>{if(!user){navigate('/auth');return;}const wasLiked=liked.includes(reel.id);setLiked(p=>wasLiked?p.filter(id=>id!==reel.id):[...p,reel.id]);setReels(p=>p.map(x=>x.id===reel.id?{...x,likes_count:Math.max(0,x.likes_count+(wasLiked?-1:1))}:x));const result=wasLiked?await supabase.from('post_likes').delete().eq('post_id',reel.id).eq('user_id',user.id):await supabase.from('post_likes').insert({post_id:reel.id,user_id:user.id});if(result.error){setLiked(p=>wasLiked?[...p,reel.id]:p.filter(id=>id!==reel.id));setReels(p=>p.map(x=>x.id===reel.id?{...x,likes_count:Math.max(0,x.likes_count+(wasLiked?1:-1))}:x));toast.error('Like failed');}};
 const save=async(reel:Reel)=>{if(!user){navigate('/auth');return;}const wasSaved=saved.includes(reel.id);const result=wasSaved?await supabase.from('bookmarks').delete().eq('post_id',reel.id).eq('user_id',user.id):await supabase.from('bookmarks').insert({post_id:reel.id,user_id:user.id});if(result.error){toast.error('Save failed');return;}setSaved(p=>wasSaved?p.filter(id=>id!==reel.id):[...p,reel.id]);toast.success(wasSaved?'Removed from saved':'Saved');};
 const share=async(reel:Reel)=>{const url=`${window.location.origin}/videos?id=${encodeURIComponent(reel.id)}`;try{if(navigator.share)await navigator.share({title:'Testagram Reel',text:reel.content??'Watch this reel',url});else throw new Error('share unavailable')}catch{try{await navigator.clipboard.writeText(url);toast.success('Link copied')}catch{toast.error('Could not share reel')}}};
 const doSearch=()=>{const q=window.prompt('Search reels',search);if(q!==null){setSearch(q);params.delete('start');setParams(params);}};
 if(loading&&!reels.length)return <div className="h-[100svh] bg-black flex items-center justify-center"><Loader2 className="w-8 h-8 text-white animate-spin"/></div>;
 return <div className="fixed inset-0 z-[90] bg-black text-white"><div className="absolute top-0 left-0 right-0 z-30 flex justify-between p-4"><button aria-label="Close Reels" onClick={()=>navigate(-1)} className="w-10 h-10 rounded-full bg-black/45 flex items-center justify-center"><X className="w-5 h-5"/></button><div className="flex gap-2"><button aria-label="Search reels" onClick={doSearch} className="w-10 h-10 rounded-full bg-black/45 flex items-center justify-center"><Search className="w-5 h-5"/></button><button aria-label={muted?'Unmute all reels':'Mute all reels'} onClick={()=>setMuted(v=>!v)} className="w-10 h-10 rounded-full bg-black/45 flex items-center justify-center">{muted?<VolumeX className="w-5 h-5"/>:<Volume2 className="w-5 h-5"/>}</button></div></div><div ref={root} className="h-full overflow-y-auto snap-y snap-mandatory overscroll-contain">{reels.map((reel,index)=><div key={reel.id} data-index={index}><ReelCard reel={reel} active={active===index} muted={muted} onMute={()=>setMuted(v=>!v)} liked={liked.includes(reel.id)} onLike={()=>void like(reel)} saved={saved.includes(reel.id)} onSave={()=>void save(reel)} onComment={()=>navigate(`/post/${reel.id}`)} onShare={()=>void share(reel)}/></div>)}{hasMore&&<div className="h-16 flex items-center justify-center"><Loader2 className="w-5 h-5 animate-spin"/></div>}</div></div>;
}
