import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
import { createClient } from 'npm:@supabase/supabase-js@2';
const url=Deno.env.get('SUPABASE_URL')!;
const service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||Deno.env.get('SUPABASE_SECRET_KEY')||'';
const db=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});
const ORIGIN='https://federation.testagram.site';
const json=(v:unknown,s=200)=>new Response(JSON.stringify(v),{status:s,headers:{'content-type':'application/json'}});
function b64(bytes:ArrayBuffer|Uint8Array){const a=new Uint8Array(bytes);let s='';for(let i=0;i<a.length;i+=0x8000)s+=String.fromCharCode(...a.subarray(i,i+0x8000));return btoa(s)}
function pem(label:string,bytes:ArrayBuffer|Uint8Array){const x=b64(bytes).match(/.{1,64}/g)?.join('\n')||'';return `-----BEGIN ${label}-----\n${x}\n-----END ${label}-----`}
async function provision(p:any){const actorUrl=`${ORIGIN}/users/${encodeURIComponent(p.username)}`;const {data:old}=await db.from('federation_actors').select('id,user_id,username,actor_url,inbox_url,public_key_pem,private_key_jwk').eq('user_id',p.id).maybeSingle();if(old?.actor_url===actorUrl&&old.public_key_pem&&old.private_key_jwk)return {username:p.username,status:'already_valid'};const kp=await crypto.subtle.generateKey({name:'RSASSA-PKCS1-v1_5',modulusLength:2048,publicExponent:new Uint8Array([1,0,1]),hash:'SHA-256'},true,['sign','verify']);const priv=await crypto.subtle.exportKey('jwk',kp.privateKey);const pub=pem('PUBLIC KEY',await crypto.subtle.exportKey('spki',kp.publicKey));const row={user_id:p.id,username:p.username,actor_url:actorUrl,inbox_url:`${actorUrl}/inbox`,public_key_pem:pub,private_key_jwk:priv};const {error}=await db.from('federation_actors').upsert(row,{onConflict:'user_id'});if(error)throw error;return {username:p.username,status:'provisioned',actor_url:actorUrl}}
Deno.serve(async req=>{if(req.method!=='POST')return json({ok:false,error:'POST required'},405);const auth=req.headers.get('authorization')||'';if(!service||auth!==`Bearer ${service}`)return json({ok:false,error:'internal authorization required'},401);const {data:profiles,error}=await db.from('profiles').select('id,username').order('created_at',{ascending:true});if(error)return json({ok:false,error:error.message},500);const results=[];for(const p of profiles||[]){try{const r=await provision(p);await db.from('federation_actor_provisioning_queue').update({processed_at:new Date().toISOString(),last_error:null,attempts:0}).eq('user_id',p.id);results.push({ok:true,...r})}catch(e){const msg=e instanceof Error?e.message:String(e);await db.from('federation_actor_provisioning_queue').update({attempts:1,last_error:msg}).eq('user_id',p.id);results.push({ok:false,username:p.username,error:msg})}}return json({ok:true,worker:'federation-reconcile-actors',scanned:(profiles||[]).length,succeeded:results.filter(x=>x.ok).length,failed:results.filter(x=>!x.ok).length,results})});