import { useEffect, useState } from 'react';
import { ExternalLink, Loader2, RefreshCw, WalletCards, CheckCircle2, AlertCircle } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/hooks/useAuth';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { toast } from 'sonner';

type WalletData={wallet?:{balance:number|string;currency:string};profile?:{username?:string;display_name?:string;avatar_url?:string}|null;transactions?:Array<{id:string;type:string;direction:string;amount:number|string;currency:string;created_at:string}>};
async function callWallet(body:Record<string,unknown>){const {data,error}=await supabase.functions.invoke('wallet-paypal',{body});if(error)throw new Error(error.message||'Wallet service request failed');if(data?.error)throw new Error(data.error);return data as WalletData&{orderId?:string;approvalUrl?:string};}

export default function WalletPayPalPanel(){
 const {user}=useAuth(); const [data,setData]=useState<WalletData>({transactions:[]}); const [amount,setAmount]=useState('10'); const [currency,setCurrency]=useState('USD'); const [loading,setLoading]=useState(true); const [paying,setPaying]=useState(false); const [message,setMessage]=useState('');
 const refresh=async()=>{if(!user)return;setLoading(true);try{setData(await callWallet({action:'wallet'}))}catch(e){setMessage(e instanceof Error?e.message:'Wallet unavailable')}finally{setLoading(false)}};
 useEffect(()=>{void refresh()},[user?.id]);
 useEffect(()=>{const p=new URLSearchParams(location.search);if(p.get('paypal')!=='success'||!user)return;const id=localStorage.getItem(`testagram-paypal-order-${user.id}`);if(!id)return;localStorage.removeItem(`testagram-paypal-order-${user.id}`);setPaying(true);callWallet({action:'capture_order',orderId:id}).then(()=>{toast.success('PayPal payment captured and added to your wallet.');void refresh()}).catch(e=>{setMessage(e instanceof Error?e.message:'Payment capture failed');toast.error('PayPal payment could not be captured.')}).finally(()=>setPaying(false))},[user?.id]);
 const start=async()=>{const value=Number(amount);if(!Number.isFinite(value)||value<=0||value>10000){toast.error('Enter an amount between 1 and 10,000.');return}setPaying(true);setMessage('');try{const r=await callWallet({action:'create_order',amount:value,currency});if(!r.orderId||!r.approvalUrl)throw new Error('PayPal did not return an approval link');localStorage.setItem(`testagram-paypal-order-${user?.id}`,r.orderId);location.assign(r.approvalUrl)}catch(e){setMessage(e instanceof Error?e.message:'Could not start PayPal checkout');toast.error(e instanceof Error?e.message:'Could not start PayPal checkout');setPaying(false)}};
 if(!user)return null;
 return <section className="rounded-3xl border border-border bg-card p-5 shadow-sm space-y-5">
  <div className="flex items-center justify-between"><div className="flex items-center gap-3 min-w-0"><Avatar className="h-11 w-11"><AvatarImage src={data.profile?.avatar_url||undefined}/><AvatarFallback>{(data.profile?.display_name||data.profile?.username||user.email||'T').slice(0,1).toUpperCase()}</AvatarFallback></Avatar><div className="min-w-0"><div className="font-bold truncate">{data.profile?.display_name||data.profile?.username||'Your wallet'}</div><div className="text-xs text-muted-foreground truncate">@{data.profile?.username||'profile'} · secured by Testagram</div></div></div><button onClick={()=>void refresh()} disabled={loading} className="p-2 rounded-xl hover:bg-muted"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/></button></div>
  <div className="rounded-2xl bg-primary/10 p-4"><div className="text-xs text-muted-foreground">Available wallet balance</div><div className="text-3xl font-black mt-1">{data.wallet?`${data.wallet.currency} ${Number(data.wallet.balance).toFixed(2)}`:'—'}</div><div className="text-xs text-muted-foreground mt-1">Real ledger balance; credited only after PayPal capture.</div></div>
  <div className="grid grid-cols-[1fr_auto] gap-2"><input value={amount} onChange={e=>setAmount(e.target.value.replace(/[^0-9.]/g,''))} inputMode="decimal" className="h-11 rounded-xl border border-border bg-background px-3" placeholder="Amount"/><select value={currency} onChange={e=>setCurrency(e.target.value)} className="h-11 rounded-xl border border-border bg-background px-3 font-semibold"><option>USD</option><option>EUR</option><option>GBP</option></select></div>
  <button onClick={()=>void start()} disabled={paying||loading} className="w-full h-12 rounded-xl bg-[#ffc439] text-black font-black flex items-center justify-center gap-2 disabled:opacity-60">{paying?<Loader2 className="h-5 w-5 animate-spin"/>:<><WalletCards className="h-5 w-5"/> Add money with PayPal <ExternalLink className="h-4 w-4"/></>}</button>
  {message&&<div className="flex gap-2 items-start rounded-xl border border-destructive/30 bg-destructive/5 p-3 text-sm"><AlertCircle className="h-4 w-4 mt-0.5 shrink-0"/><span>{message}</span></div>}
  <div><div className="font-bold mb-2">Recent wallet activity</div><div className="space-y-2 max-h-48 overflow-y-auto">{(data.transactions||[]).slice(0,8).map(tx=><div key={tx.id} className="flex items-center justify-between rounded-xl bg-muted/40 px-3 py-2 text-sm"><div><div className="font-semibold capitalize">{tx.type}</div><div className="text-[11px] text-muted-foreground">{new Date(tx.created_at).toLocaleString()}</div></div><div className={tx.direction==='credit'?'text-emerald-600 font-bold':'font-bold'}>{tx.direction==='credit'?'+':'-'}{tx.currency} {Number(tx.amount).toFixed(2)}</div></div>)}{!loading&&!(data.transactions||[]).length&&<div className="text-sm text-muted-foreground py-3">No wallet transactions yet.</div>}</div></div>
  <div className="flex items-center gap-2 text-xs text-muted-foreground"><CheckCircle2 className="h-4 w-4 text-emerald-600"/> PayPal secret stays server-side.</div>
 </section>;
}
