import { createClient } from 'npm:@supabase/supabase-js@2'
const AP='application/ld+json; profile="https://www.w3.org/ns/activitystreams", application/activity+json'
const CTX=['https://www.w3.org/ns/activitystreams','https://w3id.org/security/v1']
const PUBLIC='https://www.w3.org/ns/activitystreams#Public'
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,apikey,content-type,x-client-info','Access-Control-Allow-Methods':'POST,OPTIONS'}
const enc=(x:string)=>encodeURIComponent(x)
const b64=(x:ArrayBuffer|Uint8Array)=>btoa(String.fromCharCode(...new Uint8Array(x)))
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json','Cache-Control':'no-store'}})}
function db(env:any,path:string,init:RequestInit={}){const h=new Headers(init.headers);h.set('apikey',env.SUPABASE_SERVICE_ROLE_KEY);h.set('Authorization',`Bearer ${env.SUPABASE_SERVICE_ROLE_KEY}`);h.set('Content-Type','application/json');return fetch(`${env.SUPABASE_URL}/rest/v1/${path}`,{...init,headers:h})}
async function rows(env:any,path:string){const r=await db(env,path);if(!r.ok)throw new Error(`db ${r.status}: ${(await r.text()).slice(0,500)}`);return r.json()}
async function getUser(req:Request,env:any){const auth=req.headers.get('Authorization');if(!auth)return null;const client=createClient(env.SUPABASE_URL,env.SUPABASE_ANON_KEY,{global:{headers:{Authorization:auth}}});const {data,error}=await client.auth.getUser();return error||!data.user?null:data.user}
async function localActor(env:any,userId:string){const r=await rows(env,`federation_actors?user_id=eq.${enc(userId)}&select=*&limit=1`) as any[];if(!r[0])throw new Error('Federation actor is not provisioned for this user');return r[0]}
async function signGet(local:any,url:string){const u=new URL(url),date=new Date().toUTCString(),key=await crypto.subtle.importKey('jwk',local.private_key_jwk,{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign']);const canonical=`(request-target): get ${u.pathname}${u.search}\nhost: ${u.host}\ndate: ${date}`,sig=await crypto.subtle.sign('RSASSA-PKCS1-v1_5',key,new TextEncoder().encode(canonical));return fetch(url,{headers:{Date:date,Accept:AP,Signature:`keyId="${local.actor_url}#main-key",algorithm="rsa-sha256",headers="(request-target) host date",signature="${b64(sig)}"`,'User-Agent':'Testagram-Federation/2.0'}})}
async function signPost(local:any,url:string,body:string){const u=new URL(url),date=new Date().toUTCString(),digest=`sha-256=${b64(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(body)))}`,key=await crypto.subtle.importKey('jwk',local.private_key_jwk,{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign']),canonical=`(request-target): post ${u.pathname}${u.search}\nhost: ${u.host}\ndate: ${date}\ndigest: ${digest}`,sig=await crypto.subtle.sign('RSASSA-PKCS1-v1_5',key,new TextEncoder().encode(canonical));return fetch(url,{method:'POST',body,headers:{Date:date,Digest:digest,Accept:AP,'Content-Type':AP,Signature:`keyId="${local.actor_url}#main-key",algorithm="rsa-sha256",headers="(request-target) host date digest",signature="${b64(sig)}"`,'User-Agent':'Testagram-Federation/2.0'}})}
async function remoteActor(env:any,local:any,url:string){const cached=await rows(env,`federation_remote_actors?actor_url=eq.${enc(url)}&select=*&limit=1`) as any[];if(cached[0]&&(cached[0].shared_inbox_url||cached[0].inbox_url))return cached[0];const r=await signGet(local,url),text=await r.text();if(!r.ok)throw new Error(`Remote actor fetch ${r.status}: ${text.slice(0,500)}`);const a=JSON.parse(text),host=new URL(url).hostname,row={actor_url:url,acct:a.preferredUsername?`${a.preferredUsername}@${host}`:url,username:a.preferredUsername||'',domain:host,inbox_url:a.inbox||null,shared_inbox_url:a.endpoints?.sharedInbox||null,actor:a,fetched_at:new Date().toISOString(),updated_at:new Date().toISOString()};await db(env,'federation_remote_actors?on_conflict=actor_url',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(row)});return {...row,id:''}}
async function remoteObject(env:any,local:any,url:string){const cached=await rows(env,`federation_objects?object_url=eq.${enc(url)}&select=*&limit=1`) as any[];if(cached[0])return cached[0].object||cached[0];const r=await signGet(local,url),text=await r.text();if(!r.ok)throw new Error(`Remote object fetch ${r.status}: ${text.slice(0,500)}`);const object=JSON.parse(text);await db(env,'federation_objects?on_conflict=object_url',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({object_url:url,actor_url:typeof object.attributedTo==='string'?object.attributedTo:(object.attributedTo?.id||null),object_type:object.type||'Object',object,published_at:object.published?new Date(object.published).toISOString():null,fetched_at:new Date().toISOString(),updated_at:new Date().toISOString()})});return object}
function actorOf(o:any){return typeof o?.attributedTo==='string'?o.attributedTo:(o?.attributedTo?.id||null)}
function inboxOf(a:any){return a.shared_inbox_url||a.inbox_url||a.actor?.endpoints?.sharedInbox||a.actor?.inbox||null}
async function save(env:any,table:string,row:any){const r=await db(env,`${table}?on_conflict=id`,{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(row)});if(!r.ok)throw new Error(`save ${table}: ${(await r.text()).slice(0,500)}`)}
async function patch(env:any,table:string,id:string,status:string,error?:string){await db(env,`${table}?id=eq.${enc(id)}`,{method:'PATCH',body:JSON.stringify({status,error:error?error.slice(0,1000):null,updated_at:new Date().toISOString()})})}
Deno.serve(async req=>{
 if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors});if(req.method!=='POST')return json({error:'POST required'},405)
 const env={SUPABASE_URL:Deno.env.get('SUPABASE_URL')!,SUPABASE_ANON_KEY:Deno.env.get('SUPABASE_ANON_KEY')!,SUPABASE_SERVICE_ROLE_KEY:Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!}
 try{
  const user=await getUser(req,env);if(!user)return json({error:'Authentication required'},401)
  const input=await req.json(),type=String(input.interaction||''),objectUrl=String(input.objectUrl||''),enabled=input.enabled!==false
  if(!['like','repost','reply','quote','bookmark'].includes(type))return json({error:'Unsupported interaction'},400)
  if(!(objectUrl.startsWith('http://')||objectUrl.startsWith('https://')))return json({error:'A remote ActivityPub object URL is required'},400)
  const local=await localActor(env,user.id)
  const existing=await rows(env,`federation_remote_interactions?local_user_id=eq.${enc(user.id)}&object_url=eq.${enc(objectUrl)}&interaction_type=eq.${enc(type)}&status=neq.undone&select=*&limit=1`) as any[]
  if(!enabled){
   if(!existing[0])return json({ok:true,status:'undone',federated:false})
   if(type==='bookmark'){await db(env,`federation_remote_bookmarks?id=eq.${enc(existing[0].id)}`,{method:'PATCH',body:JSON.stringify({status:'removed',updated_at:new Date().toISOString()})});await patch(env,'federation_remote_interactions',existing[0].id,'undone');return json({ok:true,status:'undone',federated:false})}
   const remote=await remoteActor(env,local,existing[0].remote_actor_url),inbox=inboxOf(remote);if(!inbox)throw new Error('Remote actor has no inbox')
   const undo={'@context':CTX,id:`${local.actor_url}/activities/${crypto.randomUUID()}`,type:'Undo',actor:local.actor_url,object:existing[0].activity_uri},rr=await signPost(local,inbox,JSON.stringify(undo)),txt=await rr.text();await patch(env,'federation_remote_interactions',existing[0].id,rr.ok?'undone':'failed',rr.ok?undefined:txt);await patch(env,type==='like'?'federation_remote_likes':'federation_remote_reposts',existing[0].id,rr.ok?'undone':'failed',rr.ok?undefined:txt);if(!rr.ok)throw new Error(`Undo delivery ${rr.status}: ${txt.slice(0,500)}`);return json({ok:true,status:'undone',federated:true})
  }
  if(existing[0])return json({ok:true,status:existing[0].status,activityUri:existing[0].activity_uri,duplicate:true})
  const object=await remoteObject(env,local,objectUrl),remoteActorUrl=actorOf(object);if(!remoteActorUrl)throw new Error('Remote object has no attributedTo actor');const remote=await remoteActor(env,local,remoteActorUrl),inbox=inboxOf(remote);if(!inbox)throw new Error('Remote actor has no inbox')
  if(type==='bookmark'){const id=crypto.randomUUID(),row={id,local_user_id:user.id,object_url:objectUrl,remote_actor_url:remoteActorUrl,status:'local_only',payload:{object},expires_at:new Date(Date.now()+30*86400000).toISOString()};await save(env,'federation_remote_interactions',{...row,interaction_type:'bookmark'});await save(env,'federation_remote_bookmarks',row);return json({ok:true,status:'local_only',federated:false})}
  const id=crypto.randomUUID(),activityId=`${local.actor_url}/activities/${id}`;let activity:any,objectUri:string|null=null,content=String(input.content||'').trim()
  if(type==='like')activity={'@context':CTX,id:activityId,type:'Like',actor:local.actor_url,object:objectUrl,to:[remoteActorUrl]}
  else if(type==='repost')activity={'@context':CTX,id:activityId,type:'Announce',actor:local.actor_url,object:objectUrl,to:[remoteActorUrl],cc:[PUBLIC]}
  else {if(!content||content.length>5000)return json({error:`${type} content is required (max 5000 chars)`},400);objectUri=`${local.actor_url}/remote-interactions/${id}`;const note:any={id:objectUri,type:'Note',attributedTo:local.actor_url,content,published:new Date().toISOString(),to:[remoteActorUrl],cc:[PUBLIC]};if(type==='reply')note.inReplyTo=objectUrl;if(type==='quote'){note.quoteUrl=objectUrl;note.quoteUri=objectUrl;note._misskey_quote=objectUrl}activity={'@context':CTX,id:activityId,type:'Create',actor:local.actor_url,object:note,to:[remoteActorUrl],cc:[PUBLIC]}}
  const common={id,local_user_id:user.id,object_url:objectUrl,remote_actor_url:remoteActorUrl,activity_uri:activityId,target_inbox:inbox,status:'pending',payload:activity,expires_at:new Date(Date.now()+30*86400000).toISOString()}
  await save(env,'federation_remote_interactions',{...common,interaction_type:type});if(type==='like'||type==='repost')await save(env,type==='like'?'federation_remote_likes':'federation_remote_reposts',common);if(type==='reply'||type==='quote')await save(env,type==='reply'?'federation_remote_replies':'federation_remote_quotes',{...common,object_uri:objectUri,content})
  const rr=await signPost(local,inbox,JSON.stringify(activity)),txt=await rr.text(),status=rr.ok?'sent':'failed';await patch(env,'federation_remote_interactions',id,status,rr.ok?undefined:txt);if(type==='like'||type==='repost')await patch(env,type==='like'?'federation_remote_likes':'federation_remote_reposts',id,status,rr.ok?undefined:txt);if(type==='reply'||type==='quote')await patch(env,type==='reply'?'federation_remote_replies':'federation_remote_quotes',id,status,rr.ok?undefined:txt);if(!rr.ok)throw new Error(`${type} delivery ${rr.status}: ${txt.slice(0,500)}`);return json({ok:true,status,activityUri:activityId,objectUri})
 }catch(error){return json({error:error instanceof Error?error.message:'Federated interaction failed'},502)}
})
