import { createClient } from 'npm:@supabase/supabase-js@2'
const ACTIVITY_JSON='application/activity+json'
const ACTIVITY_ACCEPT='application/activity+json, application/ld+json; profile="https://www.w3.org/ns/activitystreams"'
const CTX=['https://www.w3.org/ns/activitystreams','https://w3id.org/security/v1']; const PUBLIC='https://www.w3.org/ns/activitystreams#Public'
const FED_ORIGIN='https://federation.testagram.site'
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,apikey,content-type,x-client-info','Access-Control-Allow-Methods':'POST,OPTIONS'}
const enc=(x:string)=>encodeURIComponent(x), b64=(x:ArrayBuffer|Uint8Array)=>btoa(String.fromCharCode(...new Uint8Array(x)))
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json','Cache-Control':'no-store'}})}
function db(env:any,path:string,init:RequestInit={}){const h=new Headers(init.headers);h.set('apikey',env.SUPABASE_SERVICE_ROLE_KEY);h.set('Authorization',`Bearer ${env.SUPABASE_SERVICE_ROLE_KEY}`);h.set('Content-Type','application/json');return fetch(`${env.SUPABASE_URL}/rest/v1/${path}`,{...init,headers:h})}
async function rows(env:any,path:string){const r=await db(env,path);if(!r.ok)throw new Error(`db ${r.status}: ${(await r.text()).slice(0,500)}`);return r.json()}
async function user(req:Request,env:any){const a=req.headers.get('Authorization');if(!a)return null;const c=createClient(env.SUPABASE_URL,env.SUPABASE_ANON_KEY,{global:{headers:{Authorization:a}}});const {data,error}=await c.auth.getUser();return error||!data.user?null:data.user}
function pem(spki:ArrayBuffer){const raw=new Uint8Array(spki),chunk=16384;let s='';for(let i=0;i<raw.length;i+=chunk)s+=String.fromCharCode(...raw.subarray(i,i+chunk));const base=btoa(s).match(/.{1,64}/g)?.join('\n')||'';return `-----BEGIN PUBLIC KEY-----\n${base}\n-----END PUBLIC KEY-----`}
async function localActor(env:any,id:string){const r=await rows(env,`federation_actors?user_id=eq.${enc(id)}&select=*&limit=1`) as any[];if(r[0])return r[0];const p=await rows(env,`profiles?id=eq.${enc(id)}&select=username&limit=1`) as any[];let username=String(p[0]?.username||`user-${id.slice(0,8)}`).trim().replace(/[^A-Za-z0-9_.-]/g,'-');if(!username)username=`user-${id.slice(0,8)}`;const existing=await rows(env,`federation_actors?username=eq.${enc(username)}&select=user_id&limit=1`) as any[];if(existing[0]&&existing[0].user_id!==id)username=`${username}-${id.slice(0,8)}`;const kp=await crypto.subtle.generateKey({name:'RSASSA-PKCS1-v1_5',modulusLength:2048,publicExponent:new Uint8Array([1,0,1]),hash:'SHA-256'},true,['sign','verify']);const private_key_jwk=await crypto.subtle.exportKey('jwk',kp.privateKey);const public_key_pem=pem(await crypto.subtle.exportKey('spki',kp.publicKey));const actor_url=`${FED_ORIGIN}/users/${encodeURIComponent(username)}`,inbox_url=`${actor_url}/inbox`;const row={user_id:id,username,actor_url,inbox_url,public_key_pem,private_key_jwk,updated_at:new Date().toISOString()};const ins=await db(env,'federation_actors?on_conflict=user_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify(row)});if(!ins.ok)throw new Error(`Provision federation actor ${ins.status}: ${(await ins.text()).slice(0,500)}`);const out=await ins.json() as any[];return out[0]||row}
async function signGet(local:any,url:string){const u=new URL(url),date=new Date().toUTCString(),key=await crypto.subtle.importKey('jwk',local.private_key_jwk,{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign']),s=`(request-target): get ${u.pathname}${u.search}\nhost: ${u.host}\ndate: ${date}`,sig=await crypto.subtle.sign('RSASSA-PKCS1-v1_5',key,new TextEncoder().encode(s));return fetch(url,{headers:{Date:date,Accept:ACTIVITY_ACCEPT,Signature:`keyId="${local.actor_url}#main-key",algorithm="rsa-sha256",headers="(request-target) host date",signature="${b64(sig)}"`,'User-Agent':'Testagram-Federation/3.1'}})}
async function signPost(local:any,url:string,body:string){const u=new URL(url),date=new Date().toUTCString(),digest=`sha-256=${b64(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(body)))}`,key=await crypto.subtle.importKey('jwk',local.private_key_jwk,{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign']),s=`(request-target): post ${u.pathname}${u.search}\nhost: ${u.host}\ndate: ${date}\ndigest: ${digest}`,sig=await crypto.subtle.sign('RSASSA-PKCS1-v1_5',key,new TextEncoder().encode(s));return fetch(url,{method:'POST',body,headers:{Date:date,Digest:digest,Accept:ACTIVITY_ACCEPT,'Content-Type':ACTIVITY_JSON,Signature:`keyId="${local.actor_url}#main-key",algorithm="rsa-sha256",headers="(request-target) host date digest",signature="${b64(sig)}"`,'User-Agent':'Testagram-Federation/3.1'}})}
async function remoteActor(env:any,local:any,url:string){const c=await rows(env,`federation_remote_actors?actor_url=eq.${enc(url)}&select=*&limit=1`) as any[];if(c[0]&&(c[0].shared_inbox_url||c[0].inbox_url))return c[0];const r=await signGet(local,url),t=await r.text();if(!r.ok)throw new Error(`Remote actor fetch ${r.status}: ${t.slice(0,500)}`);const a=JSON.parse(t),host=new URL(url).hostname,row={actor_url:url,acct:a.preferredUsername?`${a.preferredUsername}@${host}`:url,username:a.preferredUsername||'',domain:host,inbox_url:a.inbox||null,shared_inbox_url:a.endpoints?.sharedInbox||null,actor:a,fetched_at:new Date().toISOString(),updated_at:new Date().toISOString()};await db(env,'federation_remote_actors?on_conflict=actor_url',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(row)});return row}
async function upsertCanonicalObject(env,url:string,o:any){const actor=typeof o?.attributedTo==='string'?o.attributedTo:(o?.attributedTo?.id||null);const attachment=Array.isArray(o?.attachment)?o.attachment:[];const tags=Array.isArray(o?.tag)?o.tag:[];await db(env,'federated_objects?on_conflict=uri',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({uri:url,object_type:o?.type||'Object',actor_uri:actor,url:o?.url||url,content:o?.content||o?.name||null,summary:o?.summary||null,published_at:o?.published?new Date(o.published).toISOString():null,updated_at:o?.updated?new Date(o.updated).toISOString():null,sensitive:Boolean(o?.sensitive),in_reply_to_uri:o?.inReplyTo||null,quote_uri:o?.quoteUrl||o?.quoteUri||o?._misskey_quote||null,attachments:attachment,tags,raw_object:o||{}})});await db(env,'federation_objects?on_conflict=object_url',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({object_url:url,actor_url:actor,object_type:o?.type||'Object',object:o||{},published_at:o?.published?new Date(o.published).toISOString():null,fetched_at:new Date().toISOString(),updated_at:new Date().toISOString()})})}
async function object(env:any,local:any,url:string){const c=await rows(env,`federation_objects?object_url=eq.${enc(url)}&select=*&limit=1`) as any[];if(c[0]){const o=c[0].object||c[0];await upsertCanonicalObject(env,url,o);return o}const r=await signGet(local,url),t=await r.text();if(!r.ok)throw new Error(`Remote object fetch ${r.status}: ${t.slice(0,500)}`);const o=JSON.parse(t);await upsertCanonicalObject(env,url,o);return o}
const actorOf=(o:any)=>typeof o?.attributedTo==='string'?o.attributedTo:(o?.attributedTo?.id||null), inboxOf=(a:any)=>a.shared_inbox_url||a.inbox_url||a.actor?.endpoints?.sharedInbox||a.actor?.inbox||null
async function save(env:any,table:string,row:any,type:string){const r=await db(env,`${table}?on_conflict=id`,{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(row)});if(!r.ok)throw new Error(`save ${table}: ${(await r.text()).slice(0,500)}`);if(table==='federation_remote_interactions')await db(env,'federated_object_interactions',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({object_uri:row.object_url,local_user_id:row.local_user_id,remote_actor_uri:row.remote_actor_url,interaction_type:type,activity_uri:row.activity_uri,active:true,created_at:new Date().toISOString(),updated_at:new Date().toISOString()})})}
async function patch(env:any,table:string,id:string,status:string,error?:string){await db(env,`${table}?id=eq.${enc(id)}`,{method:'PATCH',body:JSON.stringify({status,error:error?error.slice(0,1000):null,updated_at:new Date().toISOString()})});if(table==='federation_remote_interactions'){const a=await rows(env,`federation_remote_interactions?id=eq.${enc(id)}&select=activity_uri&limit=1`) as any[];if(a[0]?.activity_uri)await db(env,`federated_object_interactions?activity_uri=eq.${enc(a[0].activity_uri)}`,{method:'PATCH',body:JSON.stringify({active:status==='sent',updated_at:new Date().toISOString()})})}}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors});if(req.method!=='POST')return json({error:'POST required'},405);const env={SUPABASE_URL:Deno.env.get('SUPABASE_URL')!,SUPABASE_ANON_KEY:Deno.env.get('SUPABASE_ANON_KEY')!,SUPABASE_SERVICE_ROLE_KEY:Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!};try{
 const u=await user(req,env);if(!u)return json({error:'Authentication required'},401);const i=await req.json(),type=String(i.interaction||''),url=String(i.objectUrl||''),enabled=i.enabled!==false;if(!['like','repost','reply','quote','bookmark'].includes(type))return json({error:'Unsupported interaction'},400);if(!(url.startsWith('http://')||url.startsWith('https://')))return json({error:'A remote ActivityPub object URL is required'},400);const local=await localActor(env,u.id);const existing=await rows(env,`federation_remote_interactions?local_user_id=eq.${enc(u.id)}&object_url=eq.${enc(url)}&interaction_type=eq.${enc(type)}&status=neq.undone&select=*&limit=1`) as any[];
 if(!enabled){if(!existing[0])return json({ok:true,status:'undone',federated:false});if(type==='bookmark'){await db(env,`federation_remote_bookmarks?id=eq.${enc(existing[0].id)}`,{method:'PATCH',body:JSON.stringify({status:'removed',updated_at:new Date().toISOString()})});await patch(env,'federation_remote_interactions',existing[0].id,'undone');return json({ok:true,status:'undone',federated:false})}const ra=await remoteActor(env,local,existing[0].remote_actor_url),inbox=inboxOf(ra);if(!inbox)throw new Error('Remote actor has no inbox');const undo={'@context':CTX,id:`${local.actor_url}/activities/${crypto.randomUUID()}`,type:'Undo',actor:local.actor_url,object:existing[0].activity_uri},rr=await signPost(local,inbox,JSON.stringify(undo)),txt=await rr.text();await patch(env,'federation_remote_interactions',existing[0].id,rr.ok?'undone':'failed',rr.ok?undefined:txt);await patch(env,type==='like'?'federation_remote_likes':type==='repost'?'federation_remote_reposts':type==='reply'?'federation_remote_replies':'federation_remote_quotes',existing[0].id,rr.ok?'undone':'failed',rr.ok?undefined:txt);if(!rr.ok)throw new Error(`Undo delivery ${rr.status}: ${txt.slice(0,500)}`);return json({ok:true,status:'undone',federated:true})}
 if(existing[0])return json({ok:true,status:existing[0].status,activityUri:existing[0].activity_uri,duplicate:true});const o=await object(env,local,url),remote=actorOf(o);if(!remote)throw new Error('Remote object has no attributedTo actor');const ra=await remoteActor(env,local,remote),inbox=inboxOf(ra);if(!inbox)throw new Error('Remote actor has no inbox');
 if(type==='bookmark'){const id=crypto.randomUUID(),row={id,local_user_id:u.id,object_url:url,remote_actor_url:remote,status:'local_only',payload:{object:o},expires_at:new Date(Date.now()+30*86400000).toISOString()};await save(env,'federation_remote_interactions',{...row,activity_uri:null,interaction_type:'bookmark'},type);await save(env,'federation_remote_bookmarks',row,type);return json({ok:true,status:'local_only',federated:false})}
 const id=crypto.randomUUID(),aid=`${local.actor_url}/activities/${id}`,content=String(i.content||'').trim();let activity:any,objectUri:string|null=null;if(type==='like')activity={'@context':CTX,id:aid,type:'Like',actor:local.actor_url,object:url,to:[remote]};else if(type==='repost')activity={'@context':CTX,id:aid,type:'Announce',actor:local.actor_url,object:url,to:[remote],cc:[PUBLIC]};else{if(!content||content.length>5000)return json({error:`${type} content is required (max 5000 chars)`},400);objectUri=`${local.actor_url}/remote-interactions/${id}`;const note:any={id:objectUri,type:'Note',attributedTo:local.actor_url,content,published:new Date().toISOString(),to:[remote],cc:[PUBLIC]};if(type==='reply')note.inReplyTo=url;if(type==='quote'){note.quoteUrl=url;note.quoteUri=url;note._misskey_quote=url}activity={'@context':CTX,id:aid,type:'Create',actor:local.actor_url,object:note,to:[remote],cc:[PUBLIC]}}
 const common={id,local_user_id:u.id,object_url:url,remote_actor_url:remote,activity_uri:aid,target_inbox:inbox,status:'pending',payload:activity,expires_at:new Date(Date.now()+30*86400000).toISOString()};await save(env,'federation_remote_interactions',{...common,interaction_type:type},type);if(type==='like'||type==='repost')await save(env,type==='like'?'federation_remote_likes':'federation_remote_reposts',common,type);if(type==='reply'||type==='quote')await save(env,type==='reply'?'federation_remote_replies':'federation_remote_quotes',{...common,object_uri:objectUri,content},type);const rr=await signPost(local,inbox,JSON.stringify(activity)),txt=await rr.text(),status=rr.ok?'sent':'failed';await patch(env,'federation_remote_interactions',id,status,rr.ok?undefined:txt);if(type==='like'||type==='repost')await patch(env,type==='like'?'federation_remote_likes':'federation_remote_reposts',id,status,rr.ok?undefined:txt);if(type==='reply'||type==='quote')await patch(env,type==='reply'?'federation_remote_replies':'federation_remote_quotes',id,status,rr.ok?undefined:txt);if(!rr.ok)throw new Error(`${type} delivery ${rr.status}: ${txt.slice(0,500)}`);return json({ok:true,status,activityUri:aid,objectUri})
}catch(e){return json({error:e instanceof Error?e.message:'Federated interaction failed'},502)}})
