/**
 * sitemap-refresh — Auto-refreshes the community sitemap on a schedule.
 *
 * This function can be triggered two ways:
 *   1. HTTP GET  /functions/v1/sitemap-refresh  (manual / CI trigger)
 *   2. Cron-like: call from a scheduled job or pingdom every 6 hours
 *
 * What it does:
 *   - Fetches top 100 public communities (sorted by member_count)
 *   - Fetches top 50 public threads (sorted by views_count)
 *   - Fetches top 50 trending hashtags (sorted by usage_count)
 *   - Builds a fresh sitemap XML and logs its size
 *   - Returns the XML directly so it can also be used as a live sitemap endpoint
 *
 * Usage as a live sitemap:
 *   Add to sitemap.xml as a sitemap index entry:
 *   <sitemap><loc>https://…/functions/v1/sitemap-refresh</loc></sitemap>
 */
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

const BASE = 'https://testagram.site';

function esc(s: string): string {
  return (s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

Deno.serve(async (req: Request) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders });

  const startMs = Date.now();

  try {
    const supabase = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '',
    );

    const now = new Date().toISOString().split('T')[0];

    // ── Parallel data fetches ───────────────────────────────────────────────
    const [
      { data: communities },
      { data: threads },
      { data: hashtags },
      { data: profiles },
    ] = await Promise.all([
      supabase
        .from('communities')
        .select('name, member_count, post_count, created_at')
        .eq('is_private', false)
        .order('member_count', { ascending: false })
        .limit(100),

      supabase
        .from('threads')
        .select('id, updated_at, views_count')
        .eq('is_published', true)
        .order('views_count', { ascending: false })
        .limit(50),

      supabase
        .from('hashtags')
        .select('tag, last_used_at')
        .order('usage_count', { ascending: false })
        .limit(50),

      supabase
        .from('user_profiles')
        .select('username, created_at')
        .eq('verified', true)
        .order('followers_count', { ascending: false })
        .limit(30),
    ]);

    // ── Build URL entries ───────────────────────────────────────────────────
    const communityUrls = (communities ?? []).map((c: any) => {
      const isActive = (c.post_count ?? 0) > 20;
      const priority = Math.min(0.95, 0.55 + Math.min(0.4, (c.member_count ?? 0) / 500));
      return `  <url>\n    <loc>${BASE}/c/${esc(c.name)}</loc>\n    <lastmod>${c.created_at?.split('T')[0] ?? now}</lastmod>\n    <changefreq>${isActive ? 'hourly' : 'daily'}</changefreq>\n    <priority>${priority.toFixed(2)}</priority>\n  </url>`;
    });

    const threadUrls = (threads ?? []).map((t: any) => {
      const priority = Math.min(0.9, 0.5 + Math.min(0.4, (t.views_count ?? 0) / 10000));
      return `  <url>\n    <loc>${BASE}/thread/${esc(t.id)}</loc>\n    <lastmod>${t.updated_at?.split('T')[0] ?? now}</lastmod>\n    <changefreq>weekly</changefreq>\n    <priority>${priority.toFixed(2)}</priority>\n  </url>`;
    });

    const hashtagUrls = (hashtags ?? []).map((h: any) =>
      `  <url>\n    <loc>${BASE}/hashtag/${esc(h.tag)}</loc>\n    <lastmod>${h.last_used_at?.split('T')[0] ?? now}</lastmod>\n    <changefreq>hourly</changefreq>\n    <priority>0.70</priority>\n  </url>`
    );

    const profileUrls = (profiles ?? []).map((p: any) =>
      `  <url>\n    <loc>${BASE}/profile/${esc(p.username)}</loc>\n    <lastmod>${p.created_at?.split('T')[0] ?? now}</lastmod>\n    <changefreq>weekly</changefreq>\n    <priority>0.65</priority>\n  </url>`
    );

    const totalUrls = communityUrls.length + threadUrls.length + hashtagUrls.length + profileUrls.length;

    const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
  <!-- Sitemap generated by sitemap-refresh edge function -->
  <!-- Generated: ${now} | Communities: ${communityUrls.length} | Threads: ${threadUrls.length} | Hashtags: ${hashtagUrls.length} | Profiles: ${profileUrls.length} | Total: ${totalUrls} -->

  <!-- ── Core Pages ── -->
  <url><loc>${BASE}/</loc><changefreq>always</changefreq><priority>1.0</priority></url>
  <url><loc>${BASE}/explore</loc><changefreq>hourly</changefreq><priority>0.9</priority></url>
  <url><loc>${BASE}/videos</loc><changefreq>always</changefreq><priority>0.9</priority></url>
  <url><loc>${BASE}/threads</loc><changefreq>hourly</changefreq><priority>0.9</priority></url>
  <url><loc>${BASE}/communities</loc><changefreq>daily</changefreq><priority>0.85</priority></url>
  <url><loc>${BASE}/spaces</loc><changefreq>always</changefreq><priority>0.85</priority></url>
  <url><loc>${BASE}/leaderboard</loc><changefreq>hourly</changefreq><priority>0.8</priority></url>
  <url><loc>${BASE}/search</loc><changefreq>always</changefreq><priority>0.8</priority></url>
  <url><loc>${BASE}/premium</loc><changefreq>weekly</changefreq><priority>0.75</priority></url>
  <url><loc>${BASE}/ai</loc><changefreq>weekly</changefreq><priority>0.7</priority></url>

  <!-- ── Communities (${communityUrls.length}) ── -->
${communityUrls.join('\n')}

  <!-- ── Threads (${threadUrls.length}) ── -->
${threadUrls.join('\n')}

  <!-- ── Hashtags (${hashtagUrls.length}) ── -->
${hashtagUrls.join('\n')}

  <!-- ── Verified Profiles (${profileUrls.length}) ── -->
${profileUrls.join('\n')}
</urlset>`;

    const elapsed = Date.now() - startMs;
    console.log(`sitemap-refresh: ${totalUrls} URLs generated in ${elapsed}ms`);

    return new Response(xml, {
      status: 200,
      headers: {
        ...corsHeaders,
        'Content-Type': 'application/xml; charset=utf-8',
        'Cache-Control': 'public, max-age=21600, stale-while-revalidate=3600',
        'X-Generated-At': now,
        'X-Total-Urls': String(totalUrls),
        'X-Generation-Ms': String(elapsed),
      },
    });
  } catch (err: any) {
    console.error('sitemap-refresh error:', err);
    return new Response(JSON.stringify({ error: err.message }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
