create or replace function public.ingest_federation_interaction() returns trigger language plpgsql security definer set search_path = public as $$
declare p jsonb := new.payload; target text; actor_uri text; itype text; obj jsonb;
begin actor_uri := new.actor_url;
if new.activity_type in ('Like','Announce') then
 target := case when jsonb_typeof(p->'object')='string' then p->>'object' else p->'object'->>'id' end;
 if target is not null and target<>'' then itype := case when new.activity_type='Like' then 'like' else 'repost' end;
  insert into public.federated_object_interactions(object_uri,remote_actor_uri,interaction_type,activity_uri,active,created_at,updated_at) values(target,actor_uri,itype,new.activity_id,true,coalesce(new.received_at,now()),now()) on conflict (object_uri,remote_actor_uri,interaction_type) where remote_actor_uri is not null do update set activity_uri=excluded.activity_uri,active=true,updated_at=now();
  insert into public.federation_remote_engagements(activity_uri,object_url,remote_actor_url,interaction_type,payload,status,received_at,updated_at,expires_at) values(new.activity_id,target,actor_uri,itype,p,'active',coalesce(new.received_at,now()),now(),now()+interval '30 days') on conflict(activity_uri) do update set status='active',payload=excluded.payload,updated_at=now(); end if;
elsif new.activity_type='Undo' then
 target := case when jsonb_typeof(p->'object')='string' then p->>'object' else p->'object'->>'id' end;
 if target is not null and target<>'' then update public.federated_object_interactions set active=false,updated_at=now() where activity_uri=target and remote_actor_uri=actor_uri; update public.federation_remote_engagements set status='undone',updated_at=now() where activity_uri=target and remote_actor_url=actor_uri; end if;
elsif new.activity_type='Create' then
 obj := case when jsonb_typeof(p->'object')='object' then p->'object' else '{}'::jsonb end; target := obj->>'inReplyTo';
 if target is not null and target<>'' then insert into public.federated_object_interactions(object_uri,remote_actor_uri,interaction_type,activity_uri,active,created_at,updated_at) values(target,actor_uri,'reply',new.activity_id,true,coalesce(new.received_at,now()),now()) on conflict (object_uri,remote_actor_uri,interaction_type) where remote_actor_uri is not null do update set activity_uri=excluded.activity_uri,active=true,updated_at=now(); insert into public.federation_remote_engagements(activity_uri,object_url,remote_actor_url,interaction_type,payload,status,received_at,updated_at,expires_at) values(new.activity_id,target,actor_uri,'reply',p,'active',coalesce(new.received_at,now()),now(),now()+interval '30 days') on conflict(activity_uri) do update set status='active',payload=excluded.payload,updated_at=now(); end if;
 target := coalesce(obj->>'quoteUrl',obj->>'quoteUri',obj->>'_misskey_quote');
 if target is not null and target<>'' then insert into public.federated_object_interactions(object_uri,remote_actor_uri,interaction_type,activity_uri,active,created_at,updated_at) values(target,actor_uri,'quote',new.activity_id,true,coalesce(new.received_at,now()),now()) on conflict (object_uri,remote_actor_uri,interaction_type) where remote_actor_uri is not null do update set activity_uri=excluded.activity_uri,active=true,updated_at=now(); insert into public.federation_remote_engagements(activity_uri,object_url,remote_actor_url,interaction_type,payload,status,received_at,updated_at,expires_at) values(new.activity_id,target,actor_uri,'quote',p,'active',coalesce(new.received_at,now()),now(),now()+interval '30 days') on conflict(activity_uri) do update set status='active',payload=excluded.payload,updated_at=now(); end if;
end if; return new; end; $$;
drop trigger if exists federation_inbox_interaction_ingest on public.federation_inbox; create trigger federation_inbox_interaction_ingest after insert on public.federation_inbox for each row execute function public.ingest_federation_interaction(); notify pgrst,'reload schema';
