begin;
create index if not exists profiles_unified_search_idx on public.profiles using gin (to_tsvector('simple',coalesce(username,'')||' '||coalesce(display_name,'')||' '||coalesce(bio,'')));
create index if not exists posts_unified_search_idx on public.posts using gin (to_tsvector('simple',coalesce(content,'')));
create index if not exists hashtags_unified_search_idx on public.hashtags using gin (to_tsvector('simple',coalesce(tag,'')));
create index if not exists communities_unified_search_idx on public.communities using gin (to_tsvector('simple',coalesce(name,'')||' '||coalesce(slug,'')||' '||coalesce(description,'')));
create index if not exists products_unified_search_idx on public.products using gin (to_tsvector('simple',coalesce(name,'')||' '||coalesce(description,'')));
create index if not exists federated_actors_unified_search_idx on public.federated_actors using gin (to_tsvector('simple',coalesce(preferred_username,'')||' '||coalesce(display_name,'')||' '||coalesce(summary,'')));
create index if not exists federated_objects_unified_search_idx on public.federated_objects using gin (to_tsvector('simple',coalesce(content,'')||' '||coalesce(summary,'')));
create index if not exists federated_instances_unified_search_idx on public.federated_instances using gin (to_tsvector('simple',coalesce(domain,'')||' '||coalesce(software_name,'')));
create or replace function public.search_everything(p_query text,p_limit integer default 40)
returns table(kind text,id text,score real,title text,subtitle text,content text,url text,source text,created_at timestamptz,actor_uri text)
language sql security definer set search_path=public as $$
with s as (select trim(regexp_replace(coalesce(p_query,''),'\\s+',' ','g')) q,least(greatest(coalesce(p_limit,40),1),80) lim),t as (select q,lim,case when q='' then null else websearch_to_tsquery('simple',q) end query from s),r as (
select 'user'::text as kind,p.id::text as id,(coalesce(ts_rank_cd(to_tsvector('simple',coalesce(p.username,'')||' '||coalesce(p.display_name,'')||' '||coalesce(p.bio,'')),t.query),0)+case when lower(p.username)=lower(t.q) then 5 when lower(p.username) like lower(t.q)||'%' then 1 else 0 end)::real as score,coalesce(nullif(p.display_name,''),p.username) as title,'@'||p.username as subtitle,coalesce(p.bio,'') as content,null::text as url,'testagram'::text as source,p.created_at as created_at,null::text as actor_uri from public.profiles p cross join t where t.q<>'' and(to_tsvector('simple',coalesce(p.username,'')||' '||coalesce(p.display_name,'')||' '||coalesce(p.bio,'')) @@ t.query or lower(p.username) like lower(t.q)||'%')
union all select 'post',p.id::text,coalesce(ts_rank_cd(to_tsvector('simple',coalesce(p.content,'')),t.query),0)::real,coalesce(nullif(pr.display_name,''),pr.username,'Testagram'),case when pr.username is null then null else '@'||pr.username end,p.content,null,'testagram',p.created_at,null from public.posts p cross join t left join public.profiles pr on pr.id=coalesce(p.author_id,p.user_id) where t.q<>'' and p.visibility='public' and to_tsvector('simple',coalesce(p.content,'')) @@ t.query
union all select 'hashtag',h.id::text,(case when lower(h.tag)=lower(regexp_replace(t.q,'^#','')) then 5 else 1 end)::real,'#'||h.tag,coalesce(h.post_count,0)::text||' posts',null,null,'testagram',h.last_used_at,null from public.hashtags h cross join t where t.q<>'' and lower(h.tag) like '%'||lower(regexp_replace(t.q,'^#',''))||'%'
union all select 'community',c.id::text,coalesce(ts_rank_cd(to_tsvector('simple',coalesce(c.name,'')||' '||coalesce(c.slug,'')||' '||coalesce(c.description,'')),t.query),0)::real,c.name,c.slug,c.description,null,'testagram',c.created_at,null from public.communities c cross join t where t.q<>'' and not c.is_private and to_tsvector('simple',coalesce(c.name,'')||' '||coalesce(c.slug,'')||' '||coalesce(c.description,'')) @@ t.query
union all select 'product',p.id::text,coalesce(ts_rank_cd(to_tsvector('simple',coalesce(p.name,'')||' '||coalesce(p.description,'')),t.query),0)::real,p.name,p.currency,p.description,p.external_url,'testagram',p.created_at,null from public.products p cross join t where t.q<>'' and to_tsvector('simple',coalesce(p.name,'')||' '||coalesce(p.description,'')) @@ t.query
union all select 'fediverse_user',a.id::text,(coalesce(ts_rank_cd(to_tsvector('simple',coalesce(a.preferred_username,'')||' '||coalesce(a.display_name,'')||' '||coalesce(a.summary,'')),t.query),0)+.25)::real,coalesce(nullif(a.display_name,''),a.preferred_username,'Fediverse user'),'@'||coalesce(a.preferred_username,'')||case when i.domain is null then '' else '@'||i.domain end,a.summary,a.uri,'fediverse',a.created_at,a.uri from public.federated_actors a cross join t left join public.federated_instances i on i.id=a.instance_id where t.q<>'' and a.discoverable and not a.suspended and to_tsvector('simple',coalesce(a.preferred_username,'')||' '||coalesce(a.display_name,'')||' '||coalesce(a.summary,'')) @@ t.query
union all select 'fediverse_post',o.id::text,coalesce(ts_rank_cd(to_tsvector('simple',coalesce(o.content,'')||' '||coalesce(o.summary,'')),t.query),0)::real,coalesce(a.display_name,a.preferred_username,'Fediverse post'),coalesce(i.domain,'Fediverse'),o.content,coalesce(o.url,o.uri),'fediverse',coalesce(o.published_at,o.created_at),o.actor_uri from public.federated_objects o cross join t left join public.federated_actors a on a.uri=o.actor_uri left join public.federated_instances i on i.id=o.instance_id where t.q<>'' and not o.sensitive and to_tsvector('simple',coalesce(o.content,'')||' '||coalesce(o.summary,'')) @@ t.query
union all select 'instance',i.id::text,(coalesce(ts_rank_cd(to_tsvector('simple',coalesce(i.domain,'')||' '||coalesce(i.software_name,'')),t.query),0)+.5)::real,i.domain,coalesce(i.software_name,'ActivityPub'),i.software_version,null,'fediverse',i.created_at,null from public.federated_instances i cross join t where t.q<>'' and i.status<>'blocked' and to_tsvector('simple',coalesce(i.domain,'')||' '||coalesce(i.software_name,'')) @@ t.query)
select r.* from r where r.score>0 order by r.score desc,r.created_at desc nulls last limit(select lim from s);
$$;
revoke all on function public.search_everything(text,integer) from public;
grant execute on function public.search_everything(text,integer) to authenticated;
commit;
