-- =============================================================================
-- Migration: Schedule daily earnings distribution + budget alerts
-- Run in Supabase SQL Editor (requires pg_cron + pg_net extensions)
-- Go to: Dashboard → Database → Extensions → enable pg_cron AND pg_net
-- =============================================================================

-- Step 1: Enable extensions (run once, as the default admin user)
--   create extension if not exists pg_cron;
--   create extension if not exists pg_net;

-- Step 2: Verify extensions are active
--   select * from pg_extension where extname in ('pg_cron','pg_net');

-- =============================================================================
-- Job A: Distribute Earnings — daily at midnight UTC
-- Pays video creator fund (tiered CPM), ad revenue share, subscription reminders,
-- detects tier upgrades, fires earnings milestone notifications.
-- =============================================================================
-- select cron.schedule(
--   'distribute-earnings-daily',
--   '0 0 * * *',
--   $$
--   select
--     net.http_post(
--       url        := 'YOUR_SUPABASE_URL/functions/v1/distribute-earnings',
--       headers    := '{"Content-Type":"application/json","Authorization":"Bearer YOUR_SERVICE_ROLE_KEY"}'::jsonb,
--       body       := '{}'::jsonb,
--       timeout_milliseconds := 30000
--     ) as request_id;
--   $$
-- );

-- =============================================================================
-- Job B: Budget Alerts — daily at 09:00 UTC
-- Checks every user's wallet budget_settings JSONB against the current month's
-- wallet_transactions. Sends platform_inbox alerts for categories at 90%+ spend.
-- =============================================================================
-- select cron.schedule(
--   'budget-alerts-daily',
--   '0 9 * * *',
--   $$
--   select
--     net.http_post(
--       url        := 'YOUR_SUPABASE_URL/functions/v1/budget-alerts',
--       headers    := '{"Content-Type":"application/json","Authorization":"Bearer YOUR_SERVICE_ROLE_KEY"}'::jsonb,
--       body       := '{}'::jsonb,
--       timeout_milliseconds := 30000
--     ) as request_id;
--   $$
-- );

-- =============================================================================
-- Job C: Trending Hashtag Alert — hourly
-- Scans trending_hashtags for tags with trend_score > 75,
-- finds posts from the last 24h using those tags, and sends
-- a platform_inbox notification once per (user, hashtag) pair per day.
-- =============================================================================
-- select cron.schedule(
--   'trending-hashtag-alert-hourly',
--   '0 * * * *',
--   $$
--   select
--     net.http_post(
--       url        := 'YOUR_SUPABASE_URL/functions/v1/trending-hashtag-alert',
--       headers    := '{"Content-Type":"application/json","Authorization":"Bearer YOUR_SERVICE_ROLE_KEY"}'::jsonb,
--       body       := '{}'::jsonb,
--       timeout_milliseconds := 20000
--     ) as request_id;
--   $$
-- );

-- =============================================================================
-- Management queries
-- =============================================================================
-- View all scheduled jobs:
--   select jobid, jobname, schedule, command from cron.job;

-- View last 20 execution runs:
--   select jobid, start_time, end_time, status, return_message
--   from cron.job_run_details
--   order by start_time desc limit 20;

-- Remove a job:
--   select cron.unschedule('distribute-earnings-daily');
--   select cron.unschedule('budget-alerts-daily');

-- =============================================================================
-- Revenue Rate Tiers Reference
-- =============================================================================
-- tier         | cpm_usd | condition
-- -------------|---------|------------------------------------------
-- top_creator  | $3.50   | verified + 100k+ total video views
-- premium      | $2.50   | verified creator
-- rising       | $2.00   | unverified + 10k+ total video views
-- standard     | $1.50   | all other creators (default)
-- =============================================================================
-- Revenue formula per video:
--   earned = floor(views / 1000) × cpm_rate
-- Example (top_creator, 50,000 views):
--   earned = floor(50000 / 1000) × $3.50 = 50 × $3.50 = $175.00
-- =============================================================================
-- Tier upgrade alerts fire when:
--   distribute-earnings detects old_tier ≠ new_tier AND new CPM > old CPM
--   → sends platform_inbox with new rate, gain per 1k, and projected revenue delta
-- =============================================================================

-- Budget alert thresholds (edge function reads from user_wallets.budget_settings):
--   90% → warning alert
--   100%+ → over-budget alert
-- Categories tracked: deposits, withdrawals, transfers, boosts, other
